// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userDefinitions.proto

package protoBuffers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position             *GlobalPosition `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated          int64           `protobuf:"zigzag64,4,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CurrentSpidID        string          `protobuf:"bytes,5,opt,name=currentSpidID,proto3" json:"currentSpidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *User) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *User) GetCurrentSpidID() string {
	if m != nil {
		return m.CurrentSpidID
	}
	return ""
}

type GetUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{3}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{4}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{6}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DeleteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{8}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestAssociationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAssociationRequest) Reset()         { *m = RequestAssociationRequest{} }
func (m *RequestAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*RequestAssociationRequest) ProtoMessage()    {}
func (*RequestAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{9}
}

func (m *RequestAssociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssociationRequest.Unmarshal(m, b)
}
func (m *RequestAssociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssociationRequest.Marshal(b, m, deterministic)
}
func (m *RequestAssociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssociationRequest.Merge(m, src)
}
func (m *RequestAssociationRequest) XXX_Size() int {
	return xxx_messageInfo_RequestAssociationRequest.Size(m)
}
func (m *RequestAssociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssociationRequest proto.InternalMessageInfo

func (m *RequestAssociationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestAssociationRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestAssociationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAssociationResponse) Reset()         { *m = RequestAssociationResponse{} }
func (m *RequestAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*RequestAssociationResponse) ProtoMessage()    {}
func (*RequestAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{10}
}

func (m *RequestAssociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssociationResponse.Unmarshal(m, b)
}
func (m *RequestAssociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssociationResponse.Marshal(b, m, deterministic)
}
func (m *RequestAssociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssociationResponse.Merge(m, src)
}
func (m *RequestAssociationResponse) XXX_Size() int {
	return xxx_messageInfo_RequestAssociationResponse.Size(m)
}
func (m *RequestAssociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssociationResponse proto.InternalMessageInfo

func (m *RequestAssociationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestAssociationResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestDissociationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDissociationRequest) Reset()         { *m = RequestDissociationRequest{} }
func (m *RequestDissociationRequest) String() string { return proto.CompactTextString(m) }
func (*RequestDissociationRequest) ProtoMessage()    {}
func (*RequestDissociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{11}
}

func (m *RequestDissociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDissociationRequest.Unmarshal(m, b)
}
func (m *RequestDissociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDissociationRequest.Marshal(b, m, deterministic)
}
func (m *RequestDissociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDissociationRequest.Merge(m, src)
}
func (m *RequestDissociationRequest) XXX_Size() int {
	return xxx_messageInfo_RequestDissociationRequest.Size(m)
}
func (m *RequestDissociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDissociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDissociationRequest proto.InternalMessageInfo

func (m *RequestDissociationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestDissociationRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestDissociationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDissociationResponse) Reset()         { *m = RequestDissociationResponse{} }
func (m *RequestDissociationResponse) String() string { return proto.CompactTextString(m) }
func (*RequestDissociationResponse) ProtoMessage()    {}
func (*RequestDissociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{12}
}

func (m *RequestDissociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDissociationResponse.Unmarshal(m, b)
}
func (m *RequestDissociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDissociationResponse.Marshal(b, m, deterministic)
}
func (m *RequestDissociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDissociationResponse.Merge(m, src)
}
func (m *RequestDissociationResponse) XXX_Size() int {
	return xxx_messageInfo_RequestDissociationResponse.Size(m)
}
func (m *RequestDissociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDissociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDissociationResponse proto.InternalMessageInfo

func (m *RequestDissociationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestDissociationResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestSpidInfoRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSpidInfoRequest) Reset()         { *m = RequestSpidInfoRequest{} }
func (m *RequestSpidInfoRequest) String() string { return proto.CompactTextString(m) }
func (*RequestSpidInfoRequest) ProtoMessage()    {}
func (*RequestSpidInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{13}
}

func (m *RequestSpidInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpidInfoRequest.Unmarshal(m, b)
}
func (m *RequestSpidInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpidInfoRequest.Marshal(b, m, deterministic)
}
func (m *RequestSpidInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpidInfoRequest.Merge(m, src)
}
func (m *RequestSpidInfoRequest) XXX_Size() int {
	return xxx_messageInfo_RequestSpidInfoRequest.Size(m)
}
func (m *RequestSpidInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpidInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpidInfoRequest proto.InternalMessageInfo

func (m *RequestSpidInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestSpidInfoRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestSpidInfoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSpidInfoResponse) Reset()         { *m = RequestSpidInfoResponse{} }
func (m *RequestSpidInfoResponse) String() string { return proto.CompactTextString(m) }
func (*RequestSpidInfoResponse) ProtoMessage()    {}
func (*RequestSpidInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{14}
}

func (m *RequestSpidInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpidInfoResponse.Unmarshal(m, b)
}
func (m *RequestSpidInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpidInfoResponse.Marshal(b, m, deterministic)
}
func (m *RequestSpidInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpidInfoResponse.Merge(m, src)
}
func (m *RequestSpidInfoResponse) XXX_Size() int {
	return xxx_messageInfo_RequestSpidInfoResponse.Size(m)
}
func (m *RequestSpidInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpidInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpidInfoResponse proto.InternalMessageInfo

func (m *RequestSpidInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestSpidInfoResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RequestLockChangeRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	LockState            string   `protobuf:"bytes,3,opt,name=lockState,proto3" json:"lockState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLockChangeRequest) Reset()         { *m = RequestLockChangeRequest{} }
func (m *RequestLockChangeRequest) String() string { return proto.CompactTextString(m) }
func (*RequestLockChangeRequest) ProtoMessage()    {}
func (*RequestLockChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{15}
}

func (m *RequestLockChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLockChangeRequest.Unmarshal(m, b)
}
func (m *RequestLockChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLockChangeRequest.Marshal(b, m, deterministic)
}
func (m *RequestLockChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLockChangeRequest.Merge(m, src)
}
func (m *RequestLockChangeRequest) XXX_Size() int {
	return xxx_messageInfo_RequestLockChangeRequest.Size(m)
}
func (m *RequestLockChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLockChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLockChangeRequest proto.InternalMessageInfo

func (m *RequestLockChangeRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestLockChangeRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

func (m *RequestLockChangeRequest) GetLockState() string {
	if m != nil {
		return m.LockState
	}
	return ""
}

type RequestLockChangeResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLockChangeResponse) Reset()         { *m = RequestLockChangeResponse{} }
func (m *RequestLockChangeResponse) String() string { return proto.CompactTextString(m) }
func (*RequestLockChangeResponse) ProtoMessage()    {}
func (*RequestLockChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{16}
}

func (m *RequestLockChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLockChangeResponse.Unmarshal(m, b)
}
func (m *RequestLockChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLockChangeResponse.Marshal(b, m, deterministic)
}
func (m *RequestLockChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLockChangeResponse.Merge(m, src)
}
func (m *RequestLockChangeResponse) XXX_Size() int {
	return xxx_messageInfo_RequestLockChangeResponse.Size(m)
}
func (m *RequestLockChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLockChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLockChangeResponse proto.InternalMessageInfo

func (m *RequestLockChangeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestLockChangeResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteUserRequest) Reset()         { *m = AddRemoteUserRequest{} }
func (m *AddRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoteUserRequest) ProtoMessage()    {}
func (*AddRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{17}
}

func (m *AddRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteUserRequest.Unmarshal(m, b)
}
func (m *AddRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *AddRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteUserRequest.Merge(m, src)
}
func (m *AddRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoteUserRequest.Size(m)
}
func (m *AddRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteUserRequest proto.InternalMessageInfo

func (m *AddRemoteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AddRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteUserResponse) Reset()         { *m = AddRemoteUserResponse{} }
func (m *AddRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddRemoteUserResponse) ProtoMessage()    {}
func (*AddRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{18}
}

func (m *AddRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteUserResponse.Unmarshal(m, b)
}
func (m *AddRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *AddRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteUserResponse.Merge(m, src)
}
func (m *AddRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddRemoteUserResponse.Size(m)
}
func (m *AddRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteUserResponse proto.InternalMessageInfo

func (m *AddRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRemoteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteUserRequest) Reset()         { *m = UpdateRemoteUserRequest{} }
func (m *UpdateRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteUserRequest) ProtoMessage()    {}
func (*UpdateRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{19}
}

func (m *UpdateRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteUserRequest.Unmarshal(m, b)
}
func (m *UpdateRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteUserRequest.Merge(m, src)
}
func (m *UpdateRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteUserRequest.Size(m)
}
func (m *UpdateRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteUserRequest proto.InternalMessageInfo

func (m *UpdateRemoteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteUserResponse) Reset()         { *m = UpdateRemoteUserResponse{} }
func (m *UpdateRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteUserResponse) ProtoMessage()    {}
func (*UpdateRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{20}
}

func (m *UpdateRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteUserResponse.Unmarshal(m, b)
}
func (m *UpdateRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteUserResponse.Merge(m, src)
}
func (m *UpdateRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteUserResponse.Size(m)
}
func (m *UpdateRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteUserResponse proto.InternalMessageInfo

func (m *UpdateRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveRemoteUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteUserRequest) Reset()         { *m = RemoveRemoteUserRequest{} }
func (m *RemoveRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteUserRequest) ProtoMessage()    {}
func (*RemoveRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{21}
}

func (m *RemoveRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteUserRequest.Unmarshal(m, b)
}
func (m *RemoveRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteUserRequest.Merge(m, src)
}
func (m *RemoveRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteUserRequest.Size(m)
}
func (m *RemoveRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteUserRequest proto.InternalMessageInfo

func (m *RemoveRemoteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RemoveRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteUserResponse) Reset()         { *m = RemoveRemoteUserResponse{} }
func (m *RemoveRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteUserResponse) ProtoMessage()    {}
func (*RemoveRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{22}
}

func (m *RemoveRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteUserResponse.Unmarshal(m, b)
}
func (m *RemoveRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteUserResponse.Merge(m, src)
}
func (m *RemoveRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteUserResponse.Size(m)
}
func (m *RemoveRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteUserResponse proto.InternalMessageInfo

func (m *RemoveRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRemoteSpidsRequest struct {
	Position             *GlobalPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRemoteSpidsRequest) Reset()         { *m = GetRemoteSpidsRequest{} }
func (m *GetRemoteSpidsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRemoteSpidsRequest) ProtoMessage()    {}
func (*GetRemoteSpidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{23}
}

func (m *GetRemoteSpidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteSpidsRequest.Unmarshal(m, b)
}
func (m *GetRemoteSpidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteSpidsRequest.Marshal(b, m, deterministic)
}
func (m *GetRemoteSpidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteSpidsRequest.Merge(m, src)
}
func (m *GetRemoteSpidsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRemoteSpidsRequest.Size(m)
}
func (m *GetRemoteSpidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteSpidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteSpidsRequest proto.InternalMessageInfo

func (m *GetRemoteSpidsRequest) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

type GetRemoteSpidsResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MarshaledSpids       string   `protobuf:"bytes,2,opt,name=marshaledSpids,proto3" json:"marshaledSpids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRemoteSpidsResponse) Reset()         { *m = GetRemoteSpidsResponse{} }
func (m *GetRemoteSpidsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRemoteSpidsResponse) ProtoMessage()    {}
func (*GetRemoteSpidsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b4052297b9d864d, []int{24}
}

func (m *GetRemoteSpidsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteSpidsResponse.Unmarshal(m, b)
}
func (m *GetRemoteSpidsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteSpidsResponse.Marshal(b, m, deterministic)
}
func (m *GetRemoteSpidsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteSpidsResponse.Merge(m, src)
}
func (m *GetRemoteSpidsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRemoteSpidsResponse.Size(m)
}
func (m *GetRemoteSpidsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteSpidsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteSpidsResponse proto.InternalMessageInfo

func (m *GetRemoteSpidsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetRemoteSpidsResponse) GetMarshaledSpids() string {
	if m != nil {
		return m.MarshaledSpids
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protoBuffers.User")
	proto.RegisterType((*GetUserRequest)(nil), "protoBuffers.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "protoBuffers.GetUserResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "protoBuffers.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "protoBuffers.RegisterUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "protoBuffers.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "protoBuffers.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "protoBuffers.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "protoBuffers.DeleteUserResponse")
	proto.RegisterType((*RequestAssociationRequest)(nil), "protoBuffers.RequestAssociationRequest")
	proto.RegisterType((*RequestAssociationResponse)(nil), "protoBuffers.RequestAssociationResponse")
	proto.RegisterType((*RequestDissociationRequest)(nil), "protoBuffers.RequestDissociationRequest")
	proto.RegisterType((*RequestDissociationResponse)(nil), "protoBuffers.RequestDissociationResponse")
	proto.RegisterType((*RequestSpidInfoRequest)(nil), "protoBuffers.RequestSpidInfoRequest")
	proto.RegisterType((*RequestSpidInfoResponse)(nil), "protoBuffers.RequestSpidInfoResponse")
	proto.RegisterType((*RequestLockChangeRequest)(nil), "protoBuffers.RequestLockChangeRequest")
	proto.RegisterType((*RequestLockChangeResponse)(nil), "protoBuffers.RequestLockChangeResponse")
	proto.RegisterType((*AddRemoteUserRequest)(nil), "protoBuffers.AddRemoteUserRequest")
	proto.RegisterType((*AddRemoteUserResponse)(nil), "protoBuffers.AddRemoteUserResponse")
	proto.RegisterType((*UpdateRemoteUserRequest)(nil), "protoBuffers.UpdateRemoteUserRequest")
	proto.RegisterType((*UpdateRemoteUserResponse)(nil), "protoBuffers.UpdateRemoteUserResponse")
	proto.RegisterType((*RemoveRemoteUserRequest)(nil), "protoBuffers.RemoveRemoteUserRequest")
	proto.RegisterType((*RemoveRemoteUserResponse)(nil), "protoBuffers.RemoveRemoteUserResponse")
	proto.RegisterType((*GetRemoteSpidsRequest)(nil), "protoBuffers.GetRemoteSpidsRequest")
	proto.RegisterType((*GetRemoteSpidsResponse)(nil), "protoBuffers.GetRemoteSpidsResponse")
}

func init() { proto.RegisterFile("userDefinitions.proto", fileDescriptor_2b4052297b9d864d) }

var fileDescriptor_2b4052297b9d864d = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x6f, 0x6b, 0xd3, 0x50,
	0x14, 0xc6, 0xc9, 0xac, 0xd3, 0x9e, 0x6a, 0x65, 0xd7, 0xb5, 0x8b, 0x75, 0x2f, 0x4a, 0x10, 0x29,
	0x08, 0x85, 0xcd, 0xbd, 0x10, 0x44, 0xa1, 0x1a, 0xa8, 0xc3, 0xbd, 0xd0, 0x94, 0x0d, 0x51, 0x54,
	0xee, 0x92, 0xd3, 0xf6, 0xb2, 0x24, 0x37, 0xe6, 0xdc, 0xfa, 0xa9, 0xfc, 0x90, 0x92, 0x9b, 0xdb,
	0x9a, 0xfe, 0x99, 0x9d, 0x31, 0xaf, 0xda, 0x9c, 0x9c, 0xe7, 0x79, 0x7e, 0xf7, 0xe6, 0xe4, 0x06,
	0x5a, 0x33, 0xc2, 0xd4, 0xc5, 0xb1, 0x88, 0x85, 0x12, 0x32, 0xa6, 0x7e, 0x92, 0x4a, 0x25, 0xd9,
	0x3d, 0xfd, 0xf3, 0x66, 0x36, 0x1e, 0x63, 0x4a, 0x1d, 0x7b, 0x82, 0x31, 0xa6, 0xc2, 0x5f, 0xeb,
	0xeb, 0xb4, 0x28, 0x11, 0xc1, 0x5a, 0xd9, 0xf9, 0x65, 0x41, 0xed, 0x9c, 0x30, 0x65, 0x4d, 0xd8,
	0x11, 0x81, 0x6d, 0x75, 0xad, 0x5e, 0xdd, 0xdb, 0x11, 0x01, 0x63, 0x50, 0x8b, 0x79, 0x84, 0xf6,
	0x8e, 0xae, 0xe8, 0xff, 0xec, 0x05, 0xdc, 0x4d, 0x24, 0x69, 0xbd, 0x7d, 0xab, 0x6b, 0xf5, 0x1a,
	0xc7, 0x87, 0xfd, 0x62, 0x7c, 0x7f, 0x18, 0xca, 0x4b, 0x1e, 0x7e, 0x30, 0x3d, 0xde, 0xa2, 0x9b,
	0x75, 0xa1, 0x11, 0x72, 0x52, 0xe7, 0x49, 0xc0, 0x15, 0x06, 0x76, 0xad, 0x6b, 0xf5, 0x98, 0x57,
	0x2c, 0xb1, 0x27, 0x70, 0xdf, 0x9f, 0xa5, 0x29, 0xc6, 0x6a, 0x94, 0x88, 0xe0, 0xd4, 0xb5, 0x6f,
	0xeb, 0xe0, 0xe5, 0xa2, 0xd3, 0x83, 0xe6, 0x10, 0x55, 0x06, 0xec, 0xe1, 0x8f, 0x19, 0x92, 0x62,
	0x6d, 0xd8, 0xcd, 0x36, 0xe6, 0xd4, 0x35, 0xec, 0xe6, 0xca, 0x19, 0xc1, 0x83, 0x45, 0x27, 0x25,
	0x32, 0x26, 0x64, 0x36, 0xdc, 0x89, 0x90, 0x88, 0x4f, 0xd0, 0xf4, 0xce, 0x2f, 0xd9, 0x53, 0xa8,
	0x65, 0x32, 0xbd, 0xd8, 0xc6, 0x31, 0x5b, 0x5e, 0x94, 0xf6, 0xd0, 0xf7, 0x9d, 0x57, 0xf0, 0xd0,
	0xc3, 0x89, 0x20, 0x85, 0x69, 0x91, 0x61, 0x2e, 0xb7, 0xb6, 0xc8, 0x3f, 0xc1, 0xfe, 0xb2, 0xbc,
	0x32, 0xb0, 0x97, 0xb0, 0x97, 0x6f, 0x64, 0x19, 0xac, 0x0b, 0x60, 0x45, 0x71, 0x65, 0x50, 0xcf,
	0x60, 0xcf, 0xc5, 0x10, 0x97, 0xa1, 0xae, 0x7b, 0x5e, 0x17, 0xc0, 0x8a, 0xcd, 0x95, 0x41, 0xbc,
	0x87, 0x47, 0x26, 0x7a, 0x40, 0x24, 0x7d, 0xc1, 0xf5, 0x64, 0xfe, 0x1d, 0x26, 0xab, 0x53, 0x3e,
	0x85, 0xf9, 0xf8, 0x9b, 0x2b, 0xe7, 0x1b, 0x74, 0x36, 0x99, 0x55, 0x06, 0x7b, 0xb6, 0xf0, 0x77,
	0xc5, 0xff, 0xd3, 0x7e, 0x87, 0xc7, 0x1b, 0xdd, 0x2a, 0xc3, 0x7d, 0x07, 0x6d, 0x13, 0xa0, 0x5f,
	0xcf, 0x78, 0x2c, 0xcb, 0xa2, 0x7e, 0x81, 0x83, 0x35, 0xa7, 0x9b, 0x60, 0x66, 0xf2, 0xcd, 0x98,
	0x99, 0x8f, 0xa7, 0xef, 0x3b, 0x53, 0xb0, 0x8d, 0xf9, 0x99, 0xf4, 0xaf, 0xde, 0x4e, 0x79, 0x3c,
	0xc1, 0x92, 0xa0, 0xec, 0x10, 0xea, 0xa1, 0xf4, 0xaf, 0x46, 0x8a, 0x2b, 0xd4, 0x67, 0x60, 0xdd,
	0xfb, 0x53, 0x70, 0xbe, 0x2e, 0x86, 0xad, 0x98, 0x54, 0xd9, 0x42, 0x5e, 0xc3, 0xfe, 0x20, 0x08,
	0x3c, 0x8c, 0x64, 0xb9, 0x17, 0xfd, 0x08, 0x5a, 0x2b, 0xfa, 0x6d, 0x68, 0xce, 0x00, 0x0e, 0xf2,
	0xb3, 0xa1, 0x7c, 0xea, 0x09, 0xd8, 0xeb, 0x16, 0x5b, 0x83, 0x8f, 0xb2, 0x89, 0x88, 0xe4, 0xcf,
	0x0d, 0xc1, 0xd7, 0x1d, 0x21, 0x27, 0xd9, 0x73, 0x5e, 0x95, 0x6c, 0x0d, 0xfa, 0x08, 0xad, 0x21,
	0xaa, 0x5c, 0x92, 0xed, 0x35, 0xcd, 0x63, 0x8a, 0x5f, 0x3b, 0xeb, 0x5f, 0xbe, 0x76, 0xce, 0x67,
	0x68, 0xaf, 0x5a, 0xde, 0x60, 0x06, 0x9a, 0x11, 0x4f, 0x69, 0xca, 0x43, 0x0c, 0xb4, 0xc6, 0x0c,
	0xde, 0x4a, 0xf5, 0x72, 0x57, 0x23, 0x3c, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x11, 0x23, 0x2d,
	0x30, 0x0f, 0x08, 0x00, 0x00,
}
