// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genericDefinitions.proto

package protoBuffers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalPosition struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalPosition) Reset()         { *m = GlobalPosition{} }
func (m *GlobalPosition) String() string { return proto.CompactTextString(m) }
func (*GlobalPosition) ProtoMessage()    {}
func (*GlobalPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_69495c6aa2023d6c, []int{0}
}

func (m *GlobalPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalPosition.Unmarshal(m, b)
}
func (m *GlobalPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalPosition.Marshal(b, m, deterministic)
}
func (m *GlobalPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalPosition.Merge(m, src)
}
func (m *GlobalPosition) XXX_Size() int {
	return xxx_messageInfo_GlobalPosition.Size(m)
}
func (m *GlobalPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalPosition.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalPosition proto.InternalMessageInfo

func (m *GlobalPosition) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GlobalPosition) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*GlobalPosition)(nil), "protoBuffers.GlobalPosition")
}

func init() { proto.RegisterFile("genericDefinitions.proto", fileDescriptor_69495c6aa2023d6c) }

var fileDescriptor_69495c6aa2023d6c = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4f, 0xcd, 0x4b,
	0x2d, 0xca, 0x4c, 0x76, 0x49, 0x4d, 0xcb, 0xcc, 0xcb, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x53, 0x4e, 0xa5, 0x69, 0x69, 0xa9, 0x45, 0xc5, 0x4a,
	0x5e, 0x5c, 0x7c, 0xee, 0x39, 0xf9, 0x49, 0x89, 0x39, 0x01, 0xf9, 0xc5, 0x60, 0x65, 0x42, 0x52,
	0x5c, 0x1c, 0x39, 0x89, 0x25, 0x99, 0x25, 0xa5, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x8c,
	0x41, 0x70, 0xbe, 0x90, 0x0c, 0x17, 0x67, 0x4e, 0x7e, 0x5e, 0x3a, 0x44, 0x92, 0x09, 0x2c, 0x89,
	0x10, 0x48, 0x62, 0x03, 0x9b, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x75, 0x4c, 0x6b, 0x0e,
	0x7c, 0x00, 0x00, 0x00,
}
