// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spidHandler.proto

package protoBuffers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LockInfo struct {
	Override             bool     `protobuf:"varint,1,opt,name=override,proto3" json:"override,omitempty"`
	Pending              bool     `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockInfo) Reset()         { *m = LockInfo{} }
func (m *LockInfo) String() string { return proto.CompactTextString(m) }
func (*LockInfo) ProtoMessage()    {}
func (*LockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{0}
}

func (m *LockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockInfo.Unmarshal(m, b)
}
func (m *LockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockInfo.Marshal(b, m, deterministic)
}
func (m *LockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockInfo.Merge(m, src)
}
func (m *LockInfo) XXX_Size() int {
	return xxx_messageInfo_LockInfo.Size(m)
}
func (m *LockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LockInfo proto.InternalMessageInfo

func (m *LockInfo) GetOverride() bool {
	if m != nil {
		return m.Override
	}
	return false
}

func (m *LockInfo) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

func (m *LockInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Spid struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BatteryLevel         uint32          `protobuf:"varint,2,opt,name=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	LockInfo             *LockInfo       `protobuf:"bytes,3,opt,name=lockInfo,proto3" json:"lockInfo,omitempty"`
	Location             *GlobalPosition `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	LastUpdated          string          `protobuf:"bytes,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CurrentUserID        string          `protobuf:"bytes,6,opt,name=currentUserID,proto3" json:"currentUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Spid) Reset()         { *m = Spid{} }
func (m *Spid) String() string { return proto.CompactTextString(m) }
func (*Spid) ProtoMessage()    {}
func (*Spid) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{1}
}

func (m *Spid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spid.Unmarshal(m, b)
}
func (m *Spid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spid.Marshal(b, m, deterministic)
}
func (m *Spid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spid.Merge(m, src)
}
func (m *Spid) XXX_Size() int {
	return xxx_messageInfo_Spid.Size(m)
}
func (m *Spid) XXX_DiscardUnknown() {
	xxx_messageInfo_Spid.DiscardUnknown(m)
}

var xxx_messageInfo_Spid proto.InternalMessageInfo

func (m *Spid) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Spid) GetBatteryLevel() uint32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *Spid) GetLockInfo() *LockInfo {
	if m != nil {
		return m.LockInfo
	}
	return nil
}

func (m *Spid) GetLocation() *GlobalPosition {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Spid) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func (m *Spid) GetCurrentUserID() string {
	if m != nil {
		return m.CurrentUserID
	}
	return ""
}

type GetSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidRequest) Reset()         { *m = GetSpidRequest{} }
func (m *GetSpidRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpidRequest) ProtoMessage()    {}
func (*GetSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{2}
}

func (m *GetSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidRequest.Unmarshal(m, b)
}
func (m *GetSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidRequest.Marshal(b, m, deterministic)
}
func (m *GetSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidRequest.Merge(m, src)
}
func (m *GetSpidRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpidRequest.Size(m)
}
func (m *GetSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidRequest proto.InternalMessageInfo

func (m *GetSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type GetSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidResponse) Reset()         { *m = GetSpidResponse{} }
func (m *GetSpidResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpidResponse) ProtoMessage()    {}
func (*GetSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{3}
}

func (m *GetSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidResponse.Unmarshal(m, b)
}
func (m *GetSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidResponse.Marshal(b, m, deterministic)
}
func (m *GetSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidResponse.Merge(m, src)
}
func (m *GetSpidResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpidResponse.Size(m)
}
func (m *GetSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidResponse proto.InternalMessageInfo

func (m *GetSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RegisterSpidRequest struct {
	BatteryLevel         uint32          `protobuf:"varint,2,opt,name=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	Location             *GlobalPosition `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterSpidRequest) Reset()         { *m = RegisterSpidRequest{} }
func (m *RegisterSpidRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidRequest) ProtoMessage()    {}
func (*RegisterSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{4}
}

func (m *RegisterSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidRequest.Unmarshal(m, b)
}
func (m *RegisterSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidRequest.Marshal(b, m, deterministic)
}
func (m *RegisterSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidRequest.Merge(m, src)
}
func (m *RegisterSpidRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidRequest.Size(m)
}
func (m *RegisterSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidRequest proto.InternalMessageInfo

func (m *RegisterSpidRequest) GetBatteryLevel() uint32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *RegisterSpidRequest) GetLocation() *GlobalPosition {
	if m != nil {
		return m.Location
	}
	return nil
}

type RegisterSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSpidResponse) Reset()         { *m = RegisterSpidResponse{} }
func (m *RegisterSpidResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidResponse) ProtoMessage()    {}
func (*RegisterSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{5}
}

func (m *RegisterSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidResponse.Unmarshal(m, b)
}
func (m *RegisterSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidResponse.Marshal(b, m, deterministic)
}
func (m *RegisterSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidResponse.Merge(m, src)
}
func (m *RegisterSpidResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidResponse.Size(m)
}
func (m *RegisterSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidResponse proto.InternalMessageInfo

func (m *RegisterSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidRequest) Reset()         { *m = UpdateSpidRequest{} }
func (m *UpdateSpidRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidRequest) ProtoMessage()    {}
func (*UpdateSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{6}
}

func (m *UpdateSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidRequest.Unmarshal(m, b)
}
func (m *UpdateSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidRequest.Merge(m, src)
}
func (m *UpdateSpidRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidRequest.Size(m)
}
func (m *UpdateSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidRequest proto.InternalMessageInfo

func (m *UpdateSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidResponse) Reset()         { *m = UpdateSpidResponse{} }
func (m *UpdateSpidResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidResponse) ProtoMessage()    {}
func (*UpdateSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{7}
}

func (m *UpdateSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidResponse.Unmarshal(m, b)
}
func (m *UpdateSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidResponse.Merge(m, src)
}
func (m *UpdateSpidResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidResponse.Size(m)
}
func (m *UpdateSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidResponse proto.InternalMessageInfo

func (m *UpdateSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type DeleteSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidRequest) Reset()         { *m = DeleteSpidRequest{} }
func (m *DeleteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidRequest) ProtoMessage()    {}
func (*DeleteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{8}
}

func (m *DeleteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidRequest.Unmarshal(m, b)
}
func (m *DeleteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidRequest.Merge(m, src)
}
func (m *DeleteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidRequest.Size(m)
}
func (m *DeleteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidRequest proto.InternalMessageInfo

func (m *DeleteSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type DeleteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidResponse) Reset()         { *m = DeleteSpidResponse{} }
func (m *DeleteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidResponse) ProtoMessage()    {}
func (*DeleteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{9}
}

func (m *DeleteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidResponse.Unmarshal(m, b)
}
func (m *DeleteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidResponse.Merge(m, src)
}
func (m *DeleteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidResponse.Size(m)
}
func (m *DeleteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidResponse proto.InternalMessageInfo

func (m *DeleteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

func init() {
	proto.RegisterType((*LockInfo)(nil), "spidProtoBuffers.LockInfo")
	proto.RegisterType((*Spid)(nil), "spidProtoBuffers.Spid")
	proto.RegisterType((*GetSpidRequest)(nil), "spidProtoBuffers.GetSpidRequest")
	proto.RegisterType((*GetSpidResponse)(nil), "spidProtoBuffers.GetSpidResponse")
	proto.RegisterType((*RegisterSpidRequest)(nil), "spidProtoBuffers.RegisterSpidRequest")
	proto.RegisterType((*RegisterSpidResponse)(nil), "spidProtoBuffers.RegisterSpidResponse")
	proto.RegisterType((*UpdateSpidRequest)(nil), "spidProtoBuffers.UpdateSpidRequest")
	proto.RegisterType((*UpdateSpidResponse)(nil), "spidProtoBuffers.UpdateSpidResponse")
	proto.RegisterType((*DeleteSpidRequest)(nil), "spidProtoBuffers.DeleteSpidRequest")
	proto.RegisterType((*DeleteSpidResponse)(nil), "spidProtoBuffers.DeleteSpidResponse")
}

func init() { proto.RegisterFile("spidHandler.proto", fileDescriptor_97215654e7c7179a) }

var fileDescriptor_97215654e7c7179a = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x6b, 0xd3, 0x50,
	0x14, 0x5e, 0x6a, 0x57, 0xbb, 0x93, 0x6d, 0xda, 0xe3, 0x18, 0x21, 0x4f, 0xf5, 0x3a, 0xa5, 0x28,
	0xf4, 0xa1, 0x82, 0x4f, 0x82, 0x20, 0x85, 0x59, 0xd8, 0xc3, 0xc8, 0x9c, 0xe2, 0x10, 0x24, 0xed,
	0x3d, 0x2d, 0x17, 0xe3, 0xbd, 0xf1, 0xde, 0xdb, 0x89, 0xff, 0x5c, 0x7c, 0x92, 0xdc, 0xa6, 0x69,
	0x62, 0xe2, 0xdc, 0xa0, 0x6f, 0x3d, 0xa7, 0xdf, 0xf9, 0xf2, 0x9d, 0xef, 0x3b, 0x09, 0xf4, 0x4c,
	0x2a, 0xf8, 0xbb, 0x58, 0xf2, 0x84, 0xf4, 0x30, 0xd5, 0xca, 0x2a, 0x7c, 0x98, 0xb5, 0xce, 0xb3,
	0x9f, 0x6f, 0x97, 0xf3, 0x39, 0x69, 0x13, 0x06, 0x0b, 0x92, 0xa4, 0xc5, 0x6c, 0x4c, 0x73, 0x21,
	0x85, 0x15, 0x4a, 0x9a, 0x15, 0x96, 0x7d, 0x80, 0xee, 0x99, 0x9a, 0x7d, 0x9d, 0xc8, 0xb9, 0xc2,
	0x10, 0xba, 0xea, 0x9a, 0xb4, 0x16, 0x9c, 0x02, 0xaf, 0xef, 0x0d, 0xba, 0x51, 0x51, 0x63, 0x00,
	0xf7, 0x53, 0x92, 0x5c, 0xc8, 0x45, 0xd0, 0x72, 0x7f, 0xad, 0x4b, 0x3c, 0x82, 0x5d, 0x63, 0x63,
	0x4b, 0xc1, 0xbd, 0xbe, 0x37, 0xd8, 0x8b, 0x56, 0x05, 0xfb, 0xe5, 0x41, 0xfb, 0x22, 0x15, 0x1c,
	0x0f, 0xa1, 0x25, 0xb8, 0xa3, 0xdb, 0x8b, 0x5a, 0x82, 0x23, 0x83, 0xfd, 0x69, 0x6c, 0x2d, 0xe9,
	0x9f, 0x67, 0x74, 0x4d, 0x89, 0x63, 0x3b, 0x88, 0x2a, 0x3d, 0x7c, 0x05, 0xdd, 0x24, 0x17, 0xe5,
	0x58, 0xfd, 0x51, 0x38, 0xfc, 0x7b, 0xa7, 0xe1, 0x5a, 0x76, 0x54, 0x60, 0xf1, 0xb5, 0x9b, 0x8b,
	0xb3, 0xfd, 0x82, 0xb6, 0x9b, 0xeb, 0xd7, 0xe7, 0x4e, 0x13, 0x35, 0x8d, 0x93, 0x73, 0x65, 0x9c,
	0x0f, 0x51, 0x31, 0x81, 0x7d, 0xf0, 0x93, 0xd8, 0xd8, 0xcb, 0x94, 0xc7, 0x96, 0x78, 0xb0, 0xeb,
	0x24, 0x97, 0x5b, 0x78, 0x02, 0x07, 0xb3, 0xa5, 0xd6, 0x24, 0xed, 0xa5, 0x21, 0x3d, 0x19, 0x07,
	0x1d, 0x87, 0xa9, 0x36, 0xd9, 0x00, 0x0e, 0x4f, 0xc9, 0x66, 0xcb, 0x47, 0xf4, 0x7d, 0x49, 0xc6,
	0xe2, 0x31, 0x74, 0x32, 0x19, 0x93, 0x71, 0xee, 0x43, 0x5e, 0xb1, 0x8f, 0xf0, 0xa0, 0x40, 0x9a,
	0x54, 0x49, 0xe3, 0x7c, 0xfe, 0x46, 0xc6, 0xc4, 0x0b, 0xca, 0xb1, 0xeb, 0x12, 0x9f, 0x43, 0x3b,
	0x1b, 0x73, 0x86, 0xf9, 0xa3, 0xe3, 0xfa, 0x62, 0x8e, 0xc7, 0x61, 0xd8, 0x0f, 0x78, 0x14, 0xd1,
	0x42, 0x18, 0x4b, 0xba, 0xac, 0xe3, 0x36, 0xde, 0x97, 0x3d, 0xf4, 0xee, 0xea, 0x21, 0xfb, 0x0c,
	0x47, 0xd5, 0x07, 0x6f, 0x75, 0xad, 0x37, 0xd0, 0x5b, 0x45, 0x51, 0x5e, 0x6a, 0x4d, 0xe0, 0xdd,
	0x82, 0xe0, 0x0a, 0xb0, 0x4c, 0xb0, 0x55, 0x71, 0x2f, 0xa0, 0x37, 0xa6, 0x84, 0xaa, 0xe2, 0xfe,
	0x95, 0xfc, 0x15, 0x60, 0x19, 0xbc, 0x4d, 0x21, 0xa3, 0xdf, 0x2d, 0xf0, 0x2f, 0x36, 0x1f, 0x05,
	0x7c, 0x0f, 0x7e, 0x7e, 0x65, 0xee, 0x25, 0x69, 0x8a, 0xb3, 0x72, 0xae, 0xe1, 0xe3, 0x1b, 0x10,
	0x2b, 0xa5, 0x6c, 0x07, 0xbf, 0xc0, 0x7e, 0x39, 0x69, 0x7c, 0x5a, 0x1f, 0x6a, 0x38, 0xc1, 0xf0,
	0xd9, 0xff, 0x60, 0xc5, 0x03, 0x3e, 0x01, 0x6c, 0xb2, 0xc2, 0x27, 0xf5, 0xb9, 0xda, 0x29, 0x84,
	0x27, 0x37, 0x83, 0xca, 0xd4, 0x1b, 0xf7, 0x9b, 0xa8, 0x6b, 0x41, 0x36, 0x51, 0xd7, 0x03, 0x64,
	0x3b, 0xd3, 0x8e, 0xfb, 0xac, 0xbe, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x48, 0x28, 0x94,
	0x97, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpidHandlerClient is the client API for SpidHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpidHandlerClient interface {
	GetSpidInfo(ctx context.Context, in *GetSpidRequest, opts ...grpc.CallOption) (*GetSpidResponse, error)
	RegisterSpid(ctx context.Context, in *RegisterSpidRequest, opts ...grpc.CallOption) (*RegisterSpidResponse, error)
	UpdateSpid(ctx context.Context, in *UpdateSpidRequest, opts ...grpc.CallOption) (*UpdateSpidResponse, error)
	DeleteSpid(ctx context.Context, in *DeleteSpidRequest, opts ...grpc.CallOption) (*DeleteSpidResponse, error)
}

type spidHandlerClient struct {
	cc *grpc.ClientConn
}

func NewSpidHandlerClient(cc *grpc.ClientConn) SpidHandlerClient {
	return &spidHandlerClient{cc}
}

func (c *spidHandlerClient) GetSpidInfo(ctx context.Context, in *GetSpidRequest, opts ...grpc.CallOption) (*GetSpidResponse, error) {
	out := new(GetSpidResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.SpidHandler/GetSpidInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) RegisterSpid(ctx context.Context, in *RegisterSpidRequest, opts ...grpc.CallOption) (*RegisterSpidResponse, error) {
	out := new(RegisterSpidResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.SpidHandler/RegisterSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) UpdateSpid(ctx context.Context, in *UpdateSpidRequest, opts ...grpc.CallOption) (*UpdateSpidResponse, error) {
	out := new(UpdateSpidResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.SpidHandler/UpdateSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) DeleteSpid(ctx context.Context, in *DeleteSpidRequest, opts ...grpc.CallOption) (*DeleteSpidResponse, error) {
	out := new(DeleteSpidResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.SpidHandler/DeleteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpidHandlerServer is the server API for SpidHandler service.
type SpidHandlerServer interface {
	GetSpidInfo(context.Context, *GetSpidRequest) (*GetSpidResponse, error)
	RegisterSpid(context.Context, *RegisterSpidRequest) (*RegisterSpidResponse, error)
	UpdateSpid(context.Context, *UpdateSpidRequest) (*UpdateSpidResponse, error)
	DeleteSpid(context.Context, *DeleteSpidRequest) (*DeleteSpidResponse, error)
}

// UnimplementedSpidHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedSpidHandlerServer struct {
}

func (*UnimplementedSpidHandlerServer) GetSpidInfo(ctx context.Context, req *GetSpidRequest) (*GetSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpidInfo not implemented")
}
func (*UnimplementedSpidHandlerServer) RegisterSpid(ctx context.Context, req *RegisterSpidRequest) (*RegisterSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) UpdateSpid(ctx context.Context, req *UpdateSpidRequest) (*UpdateSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) DeleteSpid(ctx context.Context, req *DeleteSpidRequest) (*DeleteSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpid not implemented")
}

func RegisterSpidHandlerServer(s *grpc.Server, srv SpidHandlerServer) {
	s.RegisterService(&_SpidHandler_serviceDesc, srv)
}

func _SpidHandler_GetSpidInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.SpidHandler/GetSpidInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, req.(*GetSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_RegisterSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.SpidHandler/RegisterSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, req.(*RegisterSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_UpdateSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).UpdateSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.SpidHandler/UpdateSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).UpdateSpid(ctx, req.(*UpdateSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_DeleteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.SpidHandler/DeleteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, req.(*DeleteSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpidHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spidProtoBuffers.SpidHandler",
	HandlerType: (*SpidHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpidInfo",
			Handler:    _SpidHandler_GetSpidInfo_Handler,
		},
		{
			MethodName: "RegisterSpid",
			Handler:    _SpidHandler_RegisterSpid_Handler,
		},
		{
			MethodName: "UpdateSpid",
			Handler:    _SpidHandler_UpdateSpid_Handler,
		},
		{
			MethodName: "DeleteSpid",
			Handler:    _SpidHandler_DeleteSpid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spidHandler.proto",
}
