// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spidDefinitions.proto

package protoBuffers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LockInfo struct {
	Override             bool     `protobuf:"varint,1,opt,name=override,proto3" json:"override,omitempty"`
	Pending              bool     `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockInfo) Reset()         { *m = LockInfo{} }
func (m *LockInfo) String() string { return proto.CompactTextString(m) }
func (*LockInfo) ProtoMessage()    {}
func (*LockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{0}
}

func (m *LockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockInfo.Unmarshal(m, b)
}
func (m *LockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockInfo.Marshal(b, m, deterministic)
}
func (m *LockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockInfo.Merge(m, src)
}
func (m *LockInfo) XXX_Size() int {
	return xxx_messageInfo_LockInfo.Size(m)
}
func (m *LockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LockInfo proto.InternalMessageInfo

func (m *LockInfo) GetOverride() bool {
	if m != nil {
		return m.Override
	}
	return false
}

func (m *LockInfo) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

func (m *LockInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Spid struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BatteryLevel         uint32          `protobuf:"varint,2,opt,name=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	LockInfo             *LockInfo       `protobuf:"bytes,3,opt,name=lockInfo,proto3" json:"lockInfo,omitempty"`
	Position             *GlobalPosition `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated          int64           `protobuf:"zigzag64,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CurrentUserID        string          `protobuf:"bytes,6,opt,name=currentUserID,proto3" json:"currentUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Spid) Reset()         { *m = Spid{} }
func (m *Spid) String() string { return proto.CompactTextString(m) }
func (*Spid) ProtoMessage()    {}
func (*Spid) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{1}
}

func (m *Spid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spid.Unmarshal(m, b)
}
func (m *Spid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spid.Marshal(b, m, deterministic)
}
func (m *Spid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spid.Merge(m, src)
}
func (m *Spid) XXX_Size() int {
	return xxx_messageInfo_Spid.Size(m)
}
func (m *Spid) XXX_DiscardUnknown() {
	xxx_messageInfo_Spid.DiscardUnknown(m)
}

var xxx_messageInfo_Spid proto.InternalMessageInfo

func (m *Spid) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Spid) GetBatteryLevel() uint32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *Spid) GetLockInfo() *LockInfo {
	if m != nil {
		return m.LockInfo
	}
	return nil
}

func (m *Spid) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Spid) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *Spid) GetCurrentUserID() string {
	if m != nil {
		return m.CurrentUserID
	}
	return ""
}

type GetSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidRequest) Reset()         { *m = GetSpidRequest{} }
func (m *GetSpidRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpidRequest) ProtoMessage()    {}
func (*GetSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{2}
}

func (m *GetSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidRequest.Unmarshal(m, b)
}
func (m *GetSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidRequest.Marshal(b, m, deterministic)
}
func (m *GetSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidRequest.Merge(m, src)
}
func (m *GetSpidRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpidRequest.Size(m)
}
func (m *GetSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidRequest proto.InternalMessageInfo

func (m *GetSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type GetSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidResponse) Reset()         { *m = GetSpidResponse{} }
func (m *GetSpidResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpidResponse) ProtoMessage()    {}
func (*GetSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{3}
}

func (m *GetSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidResponse.Unmarshal(m, b)
}
func (m *GetSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidResponse.Marshal(b, m, deterministic)
}
func (m *GetSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidResponse.Merge(m, src)
}
func (m *GetSpidResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpidResponse.Size(m)
}
func (m *GetSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidResponse proto.InternalMessageInfo

func (m *GetSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RegisterSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSpidRequest) Reset()         { *m = RegisterSpidRequest{} }
func (m *RegisterSpidRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidRequest) ProtoMessage()    {}
func (*RegisterSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{4}
}

func (m *RegisterSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidRequest.Unmarshal(m, b)
}
func (m *RegisterSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidRequest.Marshal(b, m, deterministic)
}
func (m *RegisterSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidRequest.Merge(m, src)
}
func (m *RegisterSpidRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidRequest.Size(m)
}
func (m *RegisterSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidRequest proto.InternalMessageInfo

func (m *RegisterSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RegisterSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSpidResponse) Reset()         { *m = RegisterSpidResponse{} }
func (m *RegisterSpidResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidResponse) ProtoMessage()    {}
func (*RegisterSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{5}
}

func (m *RegisterSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidResponse.Unmarshal(m, b)
}
func (m *RegisterSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidResponse.Marshal(b, m, deterministic)
}
func (m *RegisterSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidResponse.Merge(m, src)
}
func (m *RegisterSpidResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidResponse.Size(m)
}
func (m *RegisterSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidResponse proto.InternalMessageInfo

func (m *RegisterSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidRequest) Reset()         { *m = UpdateSpidRequest{} }
func (m *UpdateSpidRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidRequest) ProtoMessage()    {}
func (*UpdateSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{6}
}

func (m *UpdateSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidRequest.Unmarshal(m, b)
}
func (m *UpdateSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidRequest.Merge(m, src)
}
func (m *UpdateSpidRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidRequest.Size(m)
}
func (m *UpdateSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidRequest proto.InternalMessageInfo

func (m *UpdateSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidResponse) Reset()         { *m = UpdateSpidResponse{} }
func (m *UpdateSpidResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidResponse) ProtoMessage()    {}
func (*UpdateSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{7}
}

func (m *UpdateSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidResponse.Unmarshal(m, b)
}
func (m *UpdateSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidResponse.Merge(m, src)
}
func (m *UpdateSpidResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidResponse.Size(m)
}
func (m *UpdateSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidResponse proto.InternalMessageInfo

func (m *UpdateSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type DeleteSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidRequest) Reset()         { *m = DeleteSpidRequest{} }
func (m *DeleteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidRequest) ProtoMessage()    {}
func (*DeleteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{8}
}

func (m *DeleteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidRequest.Unmarshal(m, b)
}
func (m *DeleteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidRequest.Merge(m, src)
}
func (m *DeleteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidRequest.Size(m)
}
func (m *DeleteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidRequest proto.InternalMessageInfo

func (m *DeleteSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type DeleteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidResponse) Reset()         { *m = DeleteSpidResponse{} }
func (m *DeleteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidResponse) ProtoMessage()    {}
func (*DeleteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{9}
}

func (m *DeleteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidResponse.Unmarshal(m, b)
}
func (m *DeleteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidResponse.Merge(m, src)
}
func (m *DeleteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidResponse.Size(m)
}
func (m *DeleteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidResponse proto.InternalMessageInfo

func (m *DeleteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteSpidRequest) Reset()         { *m = AddRemoteSpidRequest{} }
func (m *AddRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoteSpidRequest) ProtoMessage()    {}
func (*AddRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{10}
}

func (m *AddRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteSpidRequest.Unmarshal(m, b)
}
func (m *AddRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *AddRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteSpidRequest.Merge(m, src)
}
func (m *AddRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoteSpidRequest.Size(m)
}
func (m *AddRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteSpidRequest proto.InternalMessageInfo

func (m *AddRemoteSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteSpidResponse) Reset()         { *m = AddRemoteSpidResponse{} }
func (m *AddRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*AddRemoteSpidResponse) ProtoMessage()    {}
func (*AddRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{11}
}

func (m *AddRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteSpidResponse.Unmarshal(m, b)
}
func (m *AddRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *AddRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteSpidResponse.Merge(m, src)
}
func (m *AddRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_AddRemoteSpidResponse.Size(m)
}
func (m *AddRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteSpidResponse proto.InternalMessageInfo

func (m *AddRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRemoteSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteSpidRequest) Reset()         { *m = UpdateRemoteSpidRequest{} }
func (m *UpdateRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteSpidRequest) ProtoMessage()    {}
func (*UpdateRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{12}
}

func (m *UpdateRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Unmarshal(m, b)
}
func (m *UpdateRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteSpidRequest.Merge(m, src)
}
func (m *UpdateRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Size(m)
}
func (m *UpdateRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteSpidRequest proto.InternalMessageInfo

func (m *UpdateRemoteSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteSpidResponse) Reset()         { *m = UpdateRemoteSpidResponse{} }
func (m *UpdateRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteSpidResponse) ProtoMessage()    {}
func (*UpdateRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{13}
}

func (m *UpdateRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Unmarshal(m, b)
}
func (m *UpdateRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteSpidResponse.Merge(m, src)
}
func (m *UpdateRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Size(m)
}
func (m *UpdateRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteSpidResponse proto.InternalMessageInfo

func (m *UpdateRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveRemoteSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteSpidRequest) Reset()         { *m = RemoveRemoteSpidRequest{} }
func (m *RemoveRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteSpidRequest) ProtoMessage()    {}
func (*RemoveRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{14}
}

func (m *RemoveRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Unmarshal(m, b)
}
func (m *RemoveRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteSpidRequest.Merge(m, src)
}
func (m *RemoveRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Size(m)
}
func (m *RemoveRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteSpidRequest proto.InternalMessageInfo

func (m *RemoveRemoteSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RemoveRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteSpidResponse) Reset()         { *m = RemoveRemoteSpidResponse{} }
func (m *RemoveRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteSpidResponse) ProtoMessage()    {}
func (*RemoveRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d56c60e8f558de77, []int{15}
}

func (m *RemoveRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Unmarshal(m, b)
}
func (m *RemoveRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteSpidResponse.Merge(m, src)
}
func (m *RemoveRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Size(m)
}
func (m *RemoveRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteSpidResponse proto.InternalMessageInfo

func (m *RemoveRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LockInfo)(nil), "protoBuffers.LockInfo")
	proto.RegisterType((*Spid)(nil), "protoBuffers.Spid")
	proto.RegisterType((*GetSpidRequest)(nil), "protoBuffers.GetSpidRequest")
	proto.RegisterType((*GetSpidResponse)(nil), "protoBuffers.GetSpidResponse")
	proto.RegisterType((*RegisterSpidRequest)(nil), "protoBuffers.RegisterSpidRequest")
	proto.RegisterType((*RegisterSpidResponse)(nil), "protoBuffers.RegisterSpidResponse")
	proto.RegisterType((*UpdateSpidRequest)(nil), "protoBuffers.UpdateSpidRequest")
	proto.RegisterType((*UpdateSpidResponse)(nil), "protoBuffers.UpdateSpidResponse")
	proto.RegisterType((*DeleteSpidRequest)(nil), "protoBuffers.DeleteSpidRequest")
	proto.RegisterType((*DeleteSpidResponse)(nil), "protoBuffers.DeleteSpidResponse")
	proto.RegisterType((*AddRemoteSpidRequest)(nil), "protoBuffers.AddRemoteSpidRequest")
	proto.RegisterType((*AddRemoteSpidResponse)(nil), "protoBuffers.AddRemoteSpidResponse")
	proto.RegisterType((*UpdateRemoteSpidRequest)(nil), "protoBuffers.UpdateRemoteSpidRequest")
	proto.RegisterType((*UpdateRemoteSpidResponse)(nil), "protoBuffers.UpdateRemoteSpidResponse")
	proto.RegisterType((*RemoveRemoteSpidRequest)(nil), "protoBuffers.RemoveRemoteSpidRequest")
	proto.RegisterType((*RemoveRemoteSpidResponse)(nil), "protoBuffers.RemoveRemoteSpidResponse")
}

func init() { proto.RegisterFile("spidDefinitions.proto", fileDescriptor_d56c60e8f558de77) }

var fileDescriptor_d56c60e8f558de77 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0xd1, 0x6a, 0xdb, 0x40,
	0x10, 0x44, 0xae, 0xe3, 0x2a, 0xeb, 0x24, 0x25, 0x5b, 0x27, 0x39, 0x42, 0x1f, 0x8c, 0x28, 0xc5,
	0x50, 0x30, 0xc4, 0xcd, 0x43, 0xa1, 0xb4, 0x90, 0x62, 0x08, 0x86, 0x3c, 0x94, 0x0b, 0x31, 0x7d,
	0x95, 0x7d, 0x6b, 0x73, 0x54, 0xb9, 0x53, 0xef, 0xce, 0x86, 0xfe, 0x75, 0x3f, 0xa1, 0xe8, 0x2c,
	0x09, 0xa9, 0x8e, 0x11, 0x18, 0x3f, 0x89, 0x5d, 0xcd, 0xcc, 0xce, 0xcc, 0xc1, 0x85, 0x4d, 0xa5,
	0x18, 0xd3, 0x42, 0x2a, 0xe9, 0xa4, 0x56, 0x76, 0x98, 0x1a, 0xed, 0x34, 0x9e, 0xf8, 0xcf, 0xf7,
	0xd5, 0x62, 0x41, 0xc6, 0x5e, 0xb3, 0x25, 0x29, 0x32, 0x72, 0xbe, 0x85, 0x8b, 0xa6, 0x10, 0x3e,
	0xe8, 0xf9, 0xaf, 0x89, 0x5a, 0x68, 0xbc, 0x86, 0x50, 0xaf, 0xc9, 0x18, 0x29, 0x88, 0x05, 0xfd,
	0x60, 0x10, 0xf2, 0x72, 0x46, 0x06, 0xaf, 0x53, 0x52, 0x42, 0xaa, 0x25, 0x6b, 0xf9, 0x5f, 0xc5,
	0x88, 0x3d, 0x38, 0xb2, 0x2e, 0x76, 0xc4, 0x5e, 0xf5, 0x83, 0xc1, 0x31, 0xdf, 0x0c, 0xd1, 0xdf,
	0x00, 0xda, 0x8f, 0xa9, 0x14, 0x78, 0x06, 0x2d, 0x29, 0xbc, 0xdc, 0x31, 0x6f, 0x49, 0x81, 0x11,
	0x9c, 0xcc, 0x62, 0xe7, 0xc8, 0xfc, 0x79, 0xa0, 0x35, 0x25, 0x5e, 0xed, 0x94, 0xd7, 0x76, 0x38,
	0x82, 0x30, 0xc9, 0x4d, 0x79, 0xd5, 0xee, 0xe8, 0x72, 0x58, 0xcd, 0x33, 0x2c, 0x2c, 0xf3, 0x12,
	0x87, 0x9f, 0x21, 0x4c, 0xb5, 0xf5, 0xd9, 0x58, 0xdb, 0x73, 0xde, 0xd5, 0x39, 0xf7, 0x89, 0x9e,
	0xc5, 0xc9, 0x8f, 0x1c, 0xc3, 0x4b, 0x34, 0xf6, 0xa1, 0x9b, 0xc4, 0xd6, 0x3d, 0xa5, 0x22, 0x76,
	0x24, 0xd8, 0x51, 0x3f, 0x18, 0x20, 0xaf, 0xae, 0xf0, 0x3d, 0x9c, 0xce, 0x57, 0xc6, 0x90, 0x72,
	0x4f, 0x96, 0xcc, 0x64, 0xcc, 0x3a, 0x3e, 0x4e, 0x7d, 0x19, 0x0d, 0xe0, 0xec, 0x9e, 0x5c, 0x16,
	0x9a, 0xd3, 0xef, 0x15, 0x59, 0x87, 0x97, 0xd0, 0xc9, 0x5e, 0x67, 0x32, 0xce, 0xf3, 0xe7, 0x53,
	0xf4, 0x08, 0x6f, 0x4a, 0xa4, 0x4d, 0xb5, 0xb2, 0xbe, 0xdf, 0x67, 0xb2, 0x36, 0x5e, 0x52, 0x8e,
	0x2d, 0x46, 0xfc, 0x00, 0xed, 0x8c, 0xe6, 0x8b, 0xea, 0x8e, 0xb0, 0x1e, 0xca, 0x6b, 0xf8, 0xff,
	0xd1, 0x57, 0x78, 0xcb, 0x69, 0x29, 0xad, 0x23, 0x53, 0xf5, 0x50, 0xd0, 0x83, 0x06, 0xfa, 0x4f,
	0xe8, 0xd5, 0xe9, 0x07, 0x33, 0xf6, 0x05, 0xce, 0x37, 0x45, 0xee, 0x63, 0x6b, 0x0a, 0x58, 0x25,
	0x1f, 0xcc, 0xd4, 0x47, 0x38, 0x1f, 0x53, 0x42, 0x75, 0x53, 0xbb, 0xde, 0x6b, 0x0a, 0x58, 0x05,
	0x1f, 0xcc, 0xc4, 0x37, 0xe8, 0xdd, 0x09, 0xc1, 0xe9, 0x59, 0xef, 0x57, 0xce, 0x0d, 0x5c, 0xfc,
	0xc7, 0x6f, 0xb2, 0x16, 0xdd, 0xc1, 0xd5, 0xa6, 0xcf, 0xfd, 0xaf, 0xde, 0x02, 0xdb, 0x96, 0x68,
	0x3c, 0x7c, 0x03, 0x57, 0x19, 0x7e, 0xfd, 0xc2, 0xe1, 0x5d, 0xb5, 0xdf, 0x02, 0xdb, 0xa6, 0x34,
	0x1d, 0x9a, 0x75, 0xbc, 0xef, 0x4f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x75, 0x33, 0x09,
	0x19, 0x05, 0x00, 0x00,
}
