// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spidHandler.proto

package protoBuffers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LockInfo struct {
	Override             bool     `protobuf:"varint,1,opt,name=override,proto3" json:"override,omitempty"`
	Pending              bool     `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockInfo) Reset()         { *m = LockInfo{} }
func (m *LockInfo) String() string { return proto.CompactTextString(m) }
func (*LockInfo) ProtoMessage()    {}
func (*LockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{0}
}

func (m *LockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockInfo.Unmarshal(m, b)
}
func (m *LockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockInfo.Marshal(b, m, deterministic)
}
func (m *LockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockInfo.Merge(m, src)
}
func (m *LockInfo) XXX_Size() int {
	return xxx_messageInfo_LockInfo.Size(m)
}
func (m *LockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LockInfo proto.InternalMessageInfo

func (m *LockInfo) GetOverride() bool {
	if m != nil {
		return m.Override
	}
	return false
}

func (m *LockInfo) GetPending() bool {
	if m != nil {
		return m.Pending
	}
	return false
}

func (m *LockInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Spid struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BatteryLevel         uint32          `protobuf:"varint,2,opt,name=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	LockInfo             *LockInfo       `protobuf:"bytes,3,opt,name=lockInfo,proto3" json:"lockInfo,omitempty"`
	Position             *GlobalPosition `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated          int64           `protobuf:"zigzag64,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CurrentUserID        string          `protobuf:"bytes,6,opt,name=currentUserID,proto3" json:"currentUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Spid) Reset()         { *m = Spid{} }
func (m *Spid) String() string { return proto.CompactTextString(m) }
func (*Spid) ProtoMessage()    {}
func (*Spid) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{1}
}

func (m *Spid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spid.Unmarshal(m, b)
}
func (m *Spid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spid.Marshal(b, m, deterministic)
}
func (m *Spid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spid.Merge(m, src)
}
func (m *Spid) XXX_Size() int {
	return xxx_messageInfo_Spid.Size(m)
}
func (m *Spid) XXX_DiscardUnknown() {
	xxx_messageInfo_Spid.DiscardUnknown(m)
}

var xxx_messageInfo_Spid proto.InternalMessageInfo

func (m *Spid) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Spid) GetBatteryLevel() uint32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *Spid) GetLockInfo() *LockInfo {
	if m != nil {
		return m.LockInfo
	}
	return nil
}

func (m *Spid) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Spid) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *Spid) GetCurrentUserID() string {
	if m != nil {
		return m.CurrentUserID
	}
	return ""
}

type GetSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidRequest) Reset()         { *m = GetSpidRequest{} }
func (m *GetSpidRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpidRequest) ProtoMessage()    {}
func (*GetSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{2}
}

func (m *GetSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidRequest.Unmarshal(m, b)
}
func (m *GetSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidRequest.Marshal(b, m, deterministic)
}
func (m *GetSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidRequest.Merge(m, src)
}
func (m *GetSpidRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpidRequest.Size(m)
}
func (m *GetSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidRequest proto.InternalMessageInfo

func (m *GetSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type GetSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpidResponse) Reset()         { *m = GetSpidResponse{} }
func (m *GetSpidResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpidResponse) ProtoMessage()    {}
func (*GetSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{3}
}

func (m *GetSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpidResponse.Unmarshal(m, b)
}
func (m *GetSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpidResponse.Marshal(b, m, deterministic)
}
func (m *GetSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpidResponse.Merge(m, src)
}
func (m *GetSpidResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpidResponse.Size(m)
}
func (m *GetSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpidResponse proto.InternalMessageInfo

func (m *GetSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RegisterSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSpidRequest) Reset()         { *m = RegisterSpidRequest{} }
func (m *RegisterSpidRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidRequest) ProtoMessage()    {}
func (*RegisterSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{4}
}

func (m *RegisterSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidRequest.Unmarshal(m, b)
}
func (m *RegisterSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidRequest.Marshal(b, m, deterministic)
}
func (m *RegisterSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidRequest.Merge(m, src)
}
func (m *RegisterSpidRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidRequest.Size(m)
}
func (m *RegisterSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidRequest proto.InternalMessageInfo

func (m *RegisterSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RegisterSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSpidResponse) Reset()         { *m = RegisterSpidResponse{} }
func (m *RegisterSpidResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterSpidResponse) ProtoMessage()    {}
func (*RegisterSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{5}
}

func (m *RegisterSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSpidResponse.Unmarshal(m, b)
}
func (m *RegisterSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSpidResponse.Marshal(b, m, deterministic)
}
func (m *RegisterSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSpidResponse.Merge(m, src)
}
func (m *RegisterSpidResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterSpidResponse.Size(m)
}
func (m *RegisterSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSpidResponse proto.InternalMessageInfo

func (m *RegisterSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidRequest) Reset()         { *m = UpdateSpidRequest{} }
func (m *UpdateSpidRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidRequest) ProtoMessage()    {}
func (*UpdateSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{6}
}

func (m *UpdateSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidRequest.Unmarshal(m, b)
}
func (m *UpdateSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidRequest.Merge(m, src)
}
func (m *UpdateSpidRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidRequest.Size(m)
}
func (m *UpdateSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidRequest proto.InternalMessageInfo

func (m *UpdateSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpidResponse) Reset()         { *m = UpdateSpidResponse{} }
func (m *UpdateSpidResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSpidResponse) ProtoMessage()    {}
func (*UpdateSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{7}
}

func (m *UpdateSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpidResponse.Unmarshal(m, b)
}
func (m *UpdateSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpidResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpidResponse.Merge(m, src)
}
func (m *UpdateSpidResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSpidResponse.Size(m)
}
func (m *UpdateSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpidResponse proto.InternalMessageInfo

func (m *UpdateSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type DeleteSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidRequest) Reset()         { *m = DeleteSpidRequest{} }
func (m *DeleteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidRequest) ProtoMessage()    {}
func (*DeleteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{8}
}

func (m *DeleteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidRequest.Unmarshal(m, b)
}
func (m *DeleteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidRequest.Merge(m, src)
}
func (m *DeleteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidRequest.Size(m)
}
func (m *DeleteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidRequest proto.InternalMessageInfo

func (m *DeleteSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type DeleteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSpidResponse) Reset()         { *m = DeleteSpidResponse{} }
func (m *DeleteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSpidResponse) ProtoMessage()    {}
func (*DeleteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{9}
}

func (m *DeleteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSpidResponse.Unmarshal(m, b)
}
func (m *DeleteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSpidResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSpidResponse.Merge(m, src)
}
func (m *DeleteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSpidResponse.Size(m)
}
func (m *DeleteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSpidResponse proto.InternalMessageInfo

func (m *DeleteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteSpidResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteSpidRequest) Reset()         { *m = AddRemoteSpidRequest{} }
func (m *AddRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoteSpidRequest) ProtoMessage()    {}
func (*AddRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{10}
}

func (m *AddRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteSpidRequest.Unmarshal(m, b)
}
func (m *AddRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *AddRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteSpidRequest.Merge(m, src)
}
func (m *AddRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoteSpidRequest.Size(m)
}
func (m *AddRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteSpidRequest proto.InternalMessageInfo

func (m *AddRemoteSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteSpidResponse) Reset()         { *m = AddRemoteSpidResponse{} }
func (m *AddRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*AddRemoteSpidResponse) ProtoMessage()    {}
func (*AddRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{11}
}

func (m *AddRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteSpidResponse.Unmarshal(m, b)
}
func (m *AddRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *AddRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteSpidResponse.Merge(m, src)
}
func (m *AddRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_AddRemoteSpidResponse.Size(m)
}
func (m *AddRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteSpidResponse proto.InternalMessageInfo

func (m *AddRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRemoteSpidRequest struct {
	Spid                 *Spid    `protobuf:"bytes,1,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteSpidRequest) Reset()         { *m = UpdateRemoteSpidRequest{} }
func (m *UpdateRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteSpidRequest) ProtoMessage()    {}
func (*UpdateRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{12}
}

func (m *UpdateRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Unmarshal(m, b)
}
func (m *UpdateRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteSpidRequest.Merge(m, src)
}
func (m *UpdateRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteSpidRequest.Size(m)
}
func (m *UpdateRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteSpidRequest proto.InternalMessageInfo

func (m *UpdateRemoteSpidRequest) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type UpdateRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteSpidResponse) Reset()         { *m = UpdateRemoteSpidResponse{} }
func (m *UpdateRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteSpidResponse) ProtoMessage()    {}
func (*UpdateRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{13}
}

func (m *UpdateRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Unmarshal(m, b)
}
func (m *UpdateRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteSpidResponse.Merge(m, src)
}
func (m *UpdateRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteSpidResponse.Size(m)
}
func (m *UpdateRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteSpidResponse proto.InternalMessageInfo

func (m *UpdateRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveRemoteSpidRequest struct {
	SpidID               string   `protobuf:"bytes,1,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteSpidRequest) Reset()         { *m = RemoveRemoteSpidRequest{} }
func (m *RemoveRemoteSpidRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteSpidRequest) ProtoMessage()    {}
func (*RemoveRemoteSpidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{14}
}

func (m *RemoveRemoteSpidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Unmarshal(m, b)
}
func (m *RemoveRemoteSpidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteSpidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteSpidRequest.Merge(m, src)
}
func (m *RemoveRemoteSpidRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteSpidRequest.Size(m)
}
func (m *RemoveRemoteSpidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteSpidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteSpidRequest proto.InternalMessageInfo

func (m *RemoveRemoteSpidRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RemoveRemoteSpidResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteSpidResponse) Reset()         { *m = RemoveRemoteSpidResponse{} }
func (m *RemoveRemoteSpidResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteSpidResponse) ProtoMessage()    {}
func (*RemoveRemoteSpidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{15}
}

func (m *RemoveRemoteSpidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Unmarshal(m, b)
}
func (m *RemoveRemoteSpidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteSpidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteSpidResponse.Merge(m, src)
}
func (m *RemoveRemoteSpidResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteSpidResponse.Size(m)
}
func (m *RemoveRemoteSpidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteSpidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteSpidResponse proto.InternalMessageInfo

func (m *RemoveRemoteSpidResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRemoteSpidsRequest struct {
	Position             *GlobalPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRemoteSpidsRequest) Reset()         { *m = GetRemoteSpidsRequest{} }
func (m *GetRemoteSpidsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRemoteSpidsRequest) ProtoMessage()    {}
func (*GetRemoteSpidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{16}
}

func (m *GetRemoteSpidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteSpidsRequest.Unmarshal(m, b)
}
func (m *GetRemoteSpidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteSpidsRequest.Marshal(b, m, deterministic)
}
func (m *GetRemoteSpidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteSpidsRequest.Merge(m, src)
}
func (m *GetRemoteSpidsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRemoteSpidsRequest.Size(m)
}
func (m *GetRemoteSpidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteSpidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteSpidsRequest proto.InternalMessageInfo

func (m *GetRemoteSpidsRequest) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

type GetRemoteSpidsResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MarshaledSpids       string   `protobuf:"bytes,2,opt,name=marshaledSpids,proto3" json:"marshaledSpids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRemoteSpidsResponse) Reset()         { *m = GetRemoteSpidsResponse{} }
func (m *GetRemoteSpidsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRemoteSpidsResponse) ProtoMessage()    {}
func (*GetRemoteSpidsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97215654e7c7179a, []int{17}
}

func (m *GetRemoteSpidsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRemoteSpidsResponse.Unmarshal(m, b)
}
func (m *GetRemoteSpidsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRemoteSpidsResponse.Marshal(b, m, deterministic)
}
func (m *GetRemoteSpidsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRemoteSpidsResponse.Merge(m, src)
}
func (m *GetRemoteSpidsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRemoteSpidsResponse.Size(m)
}
func (m *GetRemoteSpidsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRemoteSpidsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRemoteSpidsResponse proto.InternalMessageInfo

func (m *GetRemoteSpidsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetRemoteSpidsResponse) GetMarshaledSpids() string {
	if m != nil {
		return m.MarshaledSpids
	}
	return ""
}

func init() {
	proto.RegisterType((*LockInfo)(nil), "protoBuffers.LockInfo")
	proto.RegisterType((*Spid)(nil), "protoBuffers.Spid")
	proto.RegisterType((*GetSpidRequest)(nil), "protoBuffers.GetSpidRequest")
	proto.RegisterType((*GetSpidResponse)(nil), "protoBuffers.GetSpidResponse")
	proto.RegisterType((*RegisterSpidRequest)(nil), "protoBuffers.RegisterSpidRequest")
	proto.RegisterType((*RegisterSpidResponse)(nil), "protoBuffers.RegisterSpidResponse")
	proto.RegisterType((*UpdateSpidRequest)(nil), "protoBuffers.UpdateSpidRequest")
	proto.RegisterType((*UpdateSpidResponse)(nil), "protoBuffers.UpdateSpidResponse")
	proto.RegisterType((*DeleteSpidRequest)(nil), "protoBuffers.DeleteSpidRequest")
	proto.RegisterType((*DeleteSpidResponse)(nil), "protoBuffers.DeleteSpidResponse")
	proto.RegisterType((*AddRemoteSpidRequest)(nil), "protoBuffers.AddRemoteSpidRequest")
	proto.RegisterType((*AddRemoteSpidResponse)(nil), "protoBuffers.AddRemoteSpidResponse")
	proto.RegisterType((*UpdateRemoteSpidRequest)(nil), "protoBuffers.UpdateRemoteSpidRequest")
	proto.RegisterType((*UpdateRemoteSpidResponse)(nil), "protoBuffers.UpdateRemoteSpidResponse")
	proto.RegisterType((*RemoveRemoteSpidRequest)(nil), "protoBuffers.RemoveRemoteSpidRequest")
	proto.RegisterType((*RemoveRemoteSpidResponse)(nil), "protoBuffers.RemoveRemoteSpidResponse")
	proto.RegisterType((*GetRemoteSpidsRequest)(nil), "protoBuffers.GetRemoteSpidsRequest")
	proto.RegisterType((*GetRemoteSpidsResponse)(nil), "protoBuffers.GetRemoteSpidsResponse")
}

func init() { proto.RegisterFile("spidHandler.proto", fileDescriptor_97215654e7c7179a) }

var fileDescriptor_97215654e7c7179a = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x6b, 0x13, 0x4f,
	0x14, 0xed, 0xf6, 0xd7, 0xf6, 0x97, 0xde, 0xb4, 0xd5, 0x5e, 0xfb, 0x67, 0x59, 0x14, 0xe3, 0xb4,
	0x96, 0x80, 0x50, 0x68, 0xec, 0x83, 0x20, 0x0a, 0x95, 0x40, 0x2d, 0xf4, 0xc1, 0x6e, 0x68, 0x94,
	0x82, 0x0f, 0x9b, 0xcc, 0x4d, 0x5c, 0xdc, 0xec, 0xae, 0x33, 0x93, 0x80, 0x9f, 0xd6, 0xaf, 0xe0,
	0x47, 0x90, 0x4c, 0x76, 0x37, 0xfb, 0x27, 0x9b, 0x68, 0xc8, 0x53, 0x98, 0x99, 0x73, 0xce, 0x3d,
	0x77, 0x76, 0xce, 0x0d, 0xec, 0xcb, 0xd0, 0xe5, 0x1f, 0x1d, 0x9f, 0x7b, 0x24, 0xce, 0x43, 0x11,
	0xa8, 0x00, 0x77, 0xf4, 0xcf, 0x87, 0x61, 0xaf, 0x47, 0x42, 0x5a, 0x66, 0x9f, 0x7c, 0x12, 0x6e,
	0xb7, 0x49, 0x3d, 0xd7, 0x77, 0x95, 0x1b, 0xf8, 0x72, 0x82, 0x63, 0x6d, 0xa8, 0xdc, 0x06, 0xdd,
	0xef, 0x37, 0x7e, 0x2f, 0x40, 0x0b, 0x2a, 0xc1, 0x88, 0x84, 0x70, 0x39, 0x99, 0x46, 0xcd, 0xa8,
	0x57, 0xec, 0x64, 0x8d, 0x26, 0xfc, 0x1f, 0x92, 0xcf, 0x5d, 0xbf, 0x6f, 0xae, 0xeb, 0xa3, 0x78,
	0x89, 0x07, 0xb0, 0x29, 0x95, 0xa3, 0xc8, 0xfc, 0xaf, 0x66, 0xd4, 0xb7, 0xed, 0xc9, 0x82, 0xfd,
	0x36, 0x60, 0xa3, 0x15, 0xba, 0x1c, 0xf7, 0x60, 0xdd, 0xe5, 0x5a, 0x6e, 0xdb, 0x5e, 0x77, 0x39,
	0x32, 0xd8, 0xe9, 0x38, 0x4a, 0x91, 0xf8, 0x79, 0x4b, 0x23, 0xf2, 0xb4, 0xda, 0xae, 0x9d, 0xd9,
	0xc3, 0x06, 0x54, 0xbc, 0xc8, 0x94, 0x56, 0xad, 0x36, 0x8e, 0xce, 0xd3, 0xfd, 0x9c, 0xc7, 0x96,
	0xed, 0x04, 0x87, 0x6f, 0xa0, 0x12, 0x06, 0x52, 0xf7, 0x66, 0x6e, 0x68, 0xce, 0xd3, 0x2c, 0xe7,
	0xda, 0x0b, 0x3a, 0x8e, 0xf7, 0x29, 0xc2, 0xd8, 0x09, 0x1a, 0x6b, 0x50, 0xf5, 0x1c, 0xa9, 0xee,
	0x43, 0xee, 0x28, 0xe2, 0xe6, 0x66, 0xcd, 0xa8, 0xa3, 0x9d, 0xde, 0xc2, 0x53, 0xd8, 0xed, 0x0e,
	0x85, 0x20, 0x5f, 0xdd, 0x4b, 0x12, 0x37, 0x4d, 0x73, 0x4b, 0xb7, 0x93, 0xdd, 0x64, 0x75, 0xd8,
	0xbb, 0x26, 0x35, 0x6e, 0xda, 0xa6, 0x1f, 0x43, 0x92, 0x0a, 0x8f, 0x60, 0x6b, 0xfc, 0x65, 0x6e,
	0x9a, 0x51, 0xff, 0xd1, 0x8a, 0xb5, 0xe0, 0x51, 0x82, 0x94, 0x61, 0xe0, 0x4b, 0x7d, 0xbf, 0x03,
	0x92, 0xd2, 0xe9, 0x53, 0x84, 0x8d, 0x97, 0x78, 0x06, 0x1b, 0x63, 0x9a, 0xbe, 0xa8, 0x6a, 0x03,
	0xb3, 0x4d, 0x69, 0x0d, 0x7d, 0xce, 0xde, 0xc1, 0x13, 0x9b, 0xfa, 0xae, 0x54, 0x24, 0xd2, 0x1e,
	0x62, 0xba, 0xb1, 0x80, 0xfe, 0x05, 0x0e, 0xb2, 0xf4, 0x95, 0x19, 0x7b, 0x0b, 0xfb, 0x93, 0x8b,
	0x5c, 0xc6, 0x56, 0x1b, 0x30, 0x4d, 0x5e, 0x99, 0xa9, 0x57, 0xb0, 0xdf, 0x24, 0x8f, 0xb2, 0xa6,
	0xca, 0xbe, 0x57, 0x1b, 0x30, 0x0d, 0x5e, 0x99, 0x89, 0xf7, 0x70, 0x70, 0xc5, 0xb9, 0x4d, 0x83,
	0x60, 0xb9, 0xcb, 0xb9, 0x80, 0xc3, 0x1c, 0x7f, 0x91, 0x35, 0x76, 0x05, 0xc7, 0x93, 0xfb, 0x5c,
	0xbe, 0xea, 0x25, 0x98, 0x45, 0x89, 0x85, 0x85, 0x2f, 0xe0, 0x78, 0x8c, 0x1f, 0xcd, 0x28, 0x5c,
	0x76, 0xed, 0x97, 0x60, 0x16, 0x29, 0x0b, 0x0b, 0xdd, 0xc1, 0xe1, 0x35, 0xa9, 0x29, 0x45, 0xc6,
	0x65, 0xd2, 0x13, 0xc2, 0xf8, 0x97, 0x09, 0xc1, 0x1e, 0xe0, 0x28, 0x2f, 0xf9, 0x17, 0x6f, 0x60,
	0x6f, 0xe0, 0x08, 0xf9, 0xcd, 0xf1, 0x88, 0x6b, 0x8e, 0x7e, 0x0d, 0xdb, 0x76, 0x6e, 0xb7, 0xf1,
	0x6b, 0x13, 0xaa, 0xad, 0xe9, 0xf8, 0xc6, 0x5b, 0xa8, 0x46, 0xb3, 0x41, 0x8f, 0xb5, 0xbc, 0xc5,
	0xcc, 0x80, 0xb1, 0x9e, 0x95, 0x9c, 0x4e, 0xdc, 0xb1, 0x35, 0xfc, 0x0c, 0x3b, 0xe9, 0x54, 0xe3,
	0x8b, 0x2c, 0x61, 0xc6, 0xc0, 0xb0, 0xd8, 0x3c, 0x48, 0x22, 0x7c, 0x07, 0x30, 0xcd, 0x25, 0x3e,
	0xcf, 0x72, 0x0a, 0x71, 0xb7, 0x6a, 0xe5, 0x80, 0xb4, 0xe4, 0x34, 0x65, 0x79, 0xc9, 0x42, 0x58,
	0xf3, 0x92, 0xc5, 0x80, 0xb2, 0x35, 0x7c, 0x80, 0xdd, 0x4c, 0x40, 0x30, 0xd7, 0xdc, 0xac, 0xf4,
	0x59, 0x27, 0x73, 0x31, 0x89, 0x76, 0x17, 0x1e, 0xe7, 0x63, 0x80, 0x2f, 0x67, 0xb5, 0x59, 0xac,
	0x70, 0xb6, 0x08, 0x96, 0x2e, 0x92, 0x8f, 0x40, 0xbe, 0x48, 0x49, 0xaa, 0xf2, 0x45, 0xca, 0x92,
	0xc4, 0xd6, 0xf0, 0xab, 0xfe, 0xe3, 0x4a, 0x3d, 0x6f, 0x3c, 0x29, 0xbc, 0xab, 0x62, 0x9e, 0xac,
	0xd3, 0xf9, 0xa0, 0x58, 0xbe, 0xb3, 0xa5, 0x61, 0xaf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x56,
	0xe8, 0x84, 0x17, 0xa6, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpidHandlerClient is the client API for SpidHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpidHandlerClient interface {
	GetSpidInfo(ctx context.Context, in *GetSpidRequest, opts ...grpc.CallOption) (*GetSpidResponse, error)
	RegisterSpid(ctx context.Context, in *RegisterSpidRequest, opts ...grpc.CallOption) (*RegisterSpidResponse, error)
	UpdateSpid(ctx context.Context, in *UpdateSpidRequest, opts ...grpc.CallOption) (*UpdateSpidResponse, error)
	DeleteSpid(ctx context.Context, in *DeleteSpidRequest, opts ...grpc.CallOption) (*DeleteSpidResponse, error)
	AddRemoteSpid(ctx context.Context, in *AddRemoteSpidRequest, opts ...grpc.CallOption) (*AddRemoteSpidResponse, error)
	UpdateRemoteSpid(ctx context.Context, in *UpdateRemoteSpidRequest, opts ...grpc.CallOption) (*UpdateRemoteSpidResponse, error)
	RemoveRemoteSpid(ctx context.Context, in *RemoveRemoteSpidRequest, opts ...grpc.CallOption) (*RemoveRemoteSpidResponse, error)
	GetRemoteSpids(ctx context.Context, in *GetRemoteSpidsRequest, opts ...grpc.CallOption) (*GetRemoteSpidsResponse, error)
}

type spidHandlerClient struct {
	cc *grpc.ClientConn
}

func NewSpidHandlerClient(cc *grpc.ClientConn) SpidHandlerClient {
	return &spidHandlerClient{cc}
}

func (c *spidHandlerClient) GetSpidInfo(ctx context.Context, in *GetSpidRequest, opts ...grpc.CallOption) (*GetSpidResponse, error) {
	out := new(GetSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/GetSpidInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) RegisterSpid(ctx context.Context, in *RegisterSpidRequest, opts ...grpc.CallOption) (*RegisterSpidResponse, error) {
	out := new(RegisterSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/RegisterSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) UpdateSpid(ctx context.Context, in *UpdateSpidRequest, opts ...grpc.CallOption) (*UpdateSpidResponse, error) {
	out := new(UpdateSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/UpdateSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) DeleteSpid(ctx context.Context, in *DeleteSpidRequest, opts ...grpc.CallOption) (*DeleteSpidResponse, error) {
	out := new(DeleteSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/DeleteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) AddRemoteSpid(ctx context.Context, in *AddRemoteSpidRequest, opts ...grpc.CallOption) (*AddRemoteSpidResponse, error) {
	out := new(AddRemoteSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/AddRemoteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) UpdateRemoteSpid(ctx context.Context, in *UpdateRemoteSpidRequest, opts ...grpc.CallOption) (*UpdateRemoteSpidResponse, error) {
	out := new(UpdateRemoteSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/UpdateRemoteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) RemoveRemoteSpid(ctx context.Context, in *RemoveRemoteSpidRequest, opts ...grpc.CallOption) (*RemoveRemoteSpidResponse, error) {
	out := new(RemoveRemoteSpidResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/RemoveRemoteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) GetRemoteSpids(ctx context.Context, in *GetRemoteSpidsRequest, opts ...grpc.CallOption) (*GetRemoteSpidsResponse, error) {
	out := new(GetRemoteSpidsResponse)
	err := c.cc.Invoke(ctx, "/protoBuffers.SpidHandler/GetRemoteSpids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpidHandlerServer is the server API for SpidHandler service.
type SpidHandlerServer interface {
	GetSpidInfo(context.Context, *GetSpidRequest) (*GetSpidResponse, error)
	RegisterSpid(context.Context, *RegisterSpidRequest) (*RegisterSpidResponse, error)
	UpdateSpid(context.Context, *UpdateSpidRequest) (*UpdateSpidResponse, error)
	DeleteSpid(context.Context, *DeleteSpidRequest) (*DeleteSpidResponse, error)
	AddRemoteSpid(context.Context, *AddRemoteSpidRequest) (*AddRemoteSpidResponse, error)
	UpdateRemoteSpid(context.Context, *UpdateRemoteSpidRequest) (*UpdateRemoteSpidResponse, error)
	RemoveRemoteSpid(context.Context, *RemoveRemoteSpidRequest) (*RemoveRemoteSpidResponse, error)
	GetRemoteSpids(context.Context, *GetRemoteSpidsRequest) (*GetRemoteSpidsResponse, error)
}

// UnimplementedSpidHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedSpidHandlerServer struct {
}

func (*UnimplementedSpidHandlerServer) GetSpidInfo(ctx context.Context, req *GetSpidRequest) (*GetSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpidInfo not implemented")
}
func (*UnimplementedSpidHandlerServer) RegisterSpid(ctx context.Context, req *RegisterSpidRequest) (*RegisterSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) UpdateSpid(ctx context.Context, req *UpdateSpidRequest) (*UpdateSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) DeleteSpid(ctx context.Context, req *DeleteSpidRequest) (*DeleteSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) AddRemoteSpid(ctx context.Context, req *AddRemoteSpidRequest) (*AddRemoteSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRemoteSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) UpdateRemoteSpid(ctx context.Context, req *UpdateRemoteSpidRequest) (*UpdateRemoteSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemoteSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) RemoveRemoteSpid(ctx context.Context, req *RemoveRemoteSpidRequest) (*RemoveRemoteSpidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRemoteSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) GetRemoteSpids(ctx context.Context, req *GetRemoteSpidsRequest) (*GetRemoteSpidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemoteSpids not implemented")
}

func RegisterSpidHandlerServer(s *grpc.Server, srv SpidHandlerServer) {
	s.RegisterService(&_SpidHandler_serviceDesc, srv)
}

func _SpidHandler_GetSpidInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/GetSpidInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, req.(*GetSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_RegisterSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/RegisterSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, req.(*RegisterSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_UpdateSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).UpdateSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/UpdateSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).UpdateSpid(ctx, req.(*UpdateSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_DeleteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/DeleteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, req.(*DeleteSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_AddRemoteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoteSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).AddRemoteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/AddRemoteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).AddRemoteSpid(ctx, req.(*AddRemoteSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_UpdateRemoteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemoteSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).UpdateRemoteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/UpdateRemoteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).UpdateRemoteSpid(ctx, req.(*UpdateRemoteSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_RemoveRemoteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRemoteSpidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).RemoveRemoteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/RemoveRemoteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).RemoveRemoteSpid(ctx, req.(*RemoveRemoteSpidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_GetRemoteSpids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteSpidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).GetRemoteSpids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoBuffers.SpidHandler/GetRemoteSpids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).GetRemoteSpids(ctx, req.(*GetRemoteSpidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpidHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoBuffers.SpidHandler",
	HandlerType: (*SpidHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpidInfo",
			Handler:    _SpidHandler_GetSpidInfo_Handler,
		},
		{
			MethodName: "RegisterSpid",
			Handler:    _SpidHandler_RegisterSpid_Handler,
		},
		{
			MethodName: "UpdateSpid",
			Handler:    _SpidHandler_UpdateSpid_Handler,
		},
		{
			MethodName: "DeleteSpid",
			Handler:    _SpidHandler_DeleteSpid_Handler,
		},
		{
			MethodName: "AddRemoteSpid",
			Handler:    _SpidHandler_AddRemoteSpid_Handler,
		},
		{
			MethodName: "UpdateRemoteSpid",
			Handler:    _SpidHandler_UpdateRemoteSpid_Handler,
		},
		{
			MethodName: "RemoveRemoteSpid",
			Handler:    _SpidHandler_RemoveRemoteSpid_Handler,
		},
		{
			MethodName: "GetRemoteSpids",
			Handler:    _SpidHandler_GetRemoteSpids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spidHandler.proto",
}
