// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userHandler.proto

package protoBuffers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position             *GlobalPosition `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated          string          `protobuf:"bytes,4,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CurrentSpidID        string          `protobuf:"bytes,5,opt,name=currentSpidID,proto3" json:"currentSpidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *User) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func (m *User) GetCurrentSpidID() string {
	if m != nil {
		return m.CurrentSpidID
	}
	return ""
}

type GetUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserRequest struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Position             *GlobalPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{3}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUserRequest) GetPosition() *GlobalPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

type RegisterUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{4}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{6}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DeleteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{8}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestAssociationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAssociationRequest) Reset()         { *m = RequestAssociationRequest{} }
func (m *RequestAssociationRequest) String() string { return proto.CompactTextString(m) }
func (*RequestAssociationRequest) ProtoMessage()    {}
func (*RequestAssociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{9}
}

func (m *RequestAssociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssociationRequest.Unmarshal(m, b)
}
func (m *RequestAssociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssociationRequest.Marshal(b, m, deterministic)
}
func (m *RequestAssociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssociationRequest.Merge(m, src)
}
func (m *RequestAssociationRequest) XXX_Size() int {
	return xxx_messageInfo_RequestAssociationRequest.Size(m)
}
func (m *RequestAssociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssociationRequest proto.InternalMessageInfo

func (m *RequestAssociationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestAssociationRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestAssociationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAssociationResponse) Reset()         { *m = RequestAssociationResponse{} }
func (m *RequestAssociationResponse) String() string { return proto.CompactTextString(m) }
func (*RequestAssociationResponse) ProtoMessage()    {}
func (*RequestAssociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{10}
}

func (m *RequestAssociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssociationResponse.Unmarshal(m, b)
}
func (m *RequestAssociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssociationResponse.Marshal(b, m, deterministic)
}
func (m *RequestAssociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssociationResponse.Merge(m, src)
}
func (m *RequestAssociationResponse) XXX_Size() int {
	return xxx_messageInfo_RequestAssociationResponse.Size(m)
}
func (m *RequestAssociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssociationResponse proto.InternalMessageInfo

func (m *RequestAssociationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestAssociationResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestDissociationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDissociationRequest) Reset()         { *m = RequestDissociationRequest{} }
func (m *RequestDissociationRequest) String() string { return proto.CompactTextString(m) }
func (*RequestDissociationRequest) ProtoMessage()    {}
func (*RequestDissociationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{11}
}

func (m *RequestDissociationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDissociationRequest.Unmarshal(m, b)
}
func (m *RequestDissociationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDissociationRequest.Marshal(b, m, deterministic)
}
func (m *RequestDissociationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDissociationRequest.Merge(m, src)
}
func (m *RequestDissociationRequest) XXX_Size() int {
	return xxx_messageInfo_RequestDissociationRequest.Size(m)
}
func (m *RequestDissociationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDissociationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDissociationRequest proto.InternalMessageInfo

func (m *RequestDissociationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestDissociationRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestDissociationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDissociationResponse) Reset()         { *m = RequestDissociationResponse{} }
func (m *RequestDissociationResponse) String() string { return proto.CompactTextString(m) }
func (*RequestDissociationResponse) ProtoMessage()    {}
func (*RequestDissociationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{12}
}

func (m *RequestDissociationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDissociationResponse.Unmarshal(m, b)
}
func (m *RequestDissociationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDissociationResponse.Marshal(b, m, deterministic)
}
func (m *RequestDissociationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDissociationResponse.Merge(m, src)
}
func (m *RequestDissociationResponse) XXX_Size() int {
	return xxx_messageInfo_RequestDissociationResponse.Size(m)
}
func (m *RequestDissociationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDissociationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDissociationResponse proto.InternalMessageInfo

func (m *RequestDissociationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestDissociationResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RequestSpidInfoRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSpidInfoRequest) Reset()         { *m = RequestSpidInfoRequest{} }
func (m *RequestSpidInfoRequest) String() string { return proto.CompactTextString(m) }
func (*RequestSpidInfoRequest) ProtoMessage()    {}
func (*RequestSpidInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{13}
}

func (m *RequestSpidInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpidInfoRequest.Unmarshal(m, b)
}
func (m *RequestSpidInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpidInfoRequest.Marshal(b, m, deterministic)
}
func (m *RequestSpidInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpidInfoRequest.Merge(m, src)
}
func (m *RequestSpidInfoRequest) XXX_Size() int {
	return xxx_messageInfo_RequestSpidInfoRequest.Size(m)
}
func (m *RequestSpidInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpidInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpidInfoRequest proto.InternalMessageInfo

func (m *RequestSpidInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestSpidInfoRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

type RequestSpidInfoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSpidInfoResponse) Reset()         { *m = RequestSpidInfoResponse{} }
func (m *RequestSpidInfoResponse) String() string { return proto.CompactTextString(m) }
func (*RequestSpidInfoResponse) ProtoMessage()    {}
func (*RequestSpidInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{14}
}

func (m *RequestSpidInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSpidInfoResponse.Unmarshal(m, b)
}
func (m *RequestSpidInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSpidInfoResponse.Marshal(b, m, deterministic)
}
func (m *RequestSpidInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSpidInfoResponse.Merge(m, src)
}
func (m *RequestSpidInfoResponse) XXX_Size() int {
	return xxx_messageInfo_RequestSpidInfoResponse.Size(m)
}
func (m *RequestSpidInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSpidInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSpidInfoResponse proto.InternalMessageInfo

func (m *RequestSpidInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestSpidInfoResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type RequestLockChangeRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SpidID               string   `protobuf:"bytes,2,opt,name=spidID,proto3" json:"spidID,omitempty"`
	LockState            string   `protobuf:"bytes,3,opt,name=lockState,proto3" json:"lockState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLockChangeRequest) Reset()         { *m = RequestLockChangeRequest{} }
func (m *RequestLockChangeRequest) String() string { return proto.CompactTextString(m) }
func (*RequestLockChangeRequest) ProtoMessage()    {}
func (*RequestLockChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{15}
}

func (m *RequestLockChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLockChangeRequest.Unmarshal(m, b)
}
func (m *RequestLockChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLockChangeRequest.Marshal(b, m, deterministic)
}
func (m *RequestLockChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLockChangeRequest.Merge(m, src)
}
func (m *RequestLockChangeRequest) XXX_Size() int {
	return xxx_messageInfo_RequestLockChangeRequest.Size(m)
}
func (m *RequestLockChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLockChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLockChangeRequest proto.InternalMessageInfo

func (m *RequestLockChangeRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RequestLockChangeRequest) GetSpidID() string {
	if m != nil {
		return m.SpidID
	}
	return ""
}

func (m *RequestLockChangeRequest) GetLockState() string {
	if m != nil {
		return m.LockState
	}
	return ""
}

type RequestLockChangeResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Spid                 *Spid    `protobuf:"bytes,2,opt,name=spid,proto3" json:"spid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLockChangeResponse) Reset()         { *m = RequestLockChangeResponse{} }
func (m *RequestLockChangeResponse) String() string { return proto.CompactTextString(m) }
func (*RequestLockChangeResponse) ProtoMessage()    {}
func (*RequestLockChangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{16}
}

func (m *RequestLockChangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLockChangeResponse.Unmarshal(m, b)
}
func (m *RequestLockChangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLockChangeResponse.Marshal(b, m, deterministic)
}
func (m *RequestLockChangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLockChangeResponse.Merge(m, src)
}
func (m *RequestLockChangeResponse) XXX_Size() int {
	return xxx_messageInfo_RequestLockChangeResponse.Size(m)
}
func (m *RequestLockChangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLockChangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLockChangeResponse proto.InternalMessageInfo

func (m *RequestLockChangeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestLockChangeResponse) GetSpid() *Spid {
	if m != nil {
		return m.Spid
	}
	return nil
}

type AddRemoteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteUserRequest) Reset()         { *m = AddRemoteUserRequest{} }
func (m *AddRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddRemoteUserRequest) ProtoMessage()    {}
func (*AddRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{17}
}

func (m *AddRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteUserRequest.Unmarshal(m, b)
}
func (m *AddRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *AddRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteUserRequest.Merge(m, src)
}
func (m *AddRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddRemoteUserRequest.Size(m)
}
func (m *AddRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteUserRequest proto.InternalMessageInfo

func (m *AddRemoteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AddRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRemoteUserResponse) Reset()         { *m = AddRemoteUserResponse{} }
func (m *AddRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddRemoteUserResponse) ProtoMessage()    {}
func (*AddRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{18}
}

func (m *AddRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRemoteUserResponse.Unmarshal(m, b)
}
func (m *AddRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *AddRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRemoteUserResponse.Merge(m, src)
}
func (m *AddRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddRemoteUserResponse.Size(m)
}
func (m *AddRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRemoteUserResponse proto.InternalMessageInfo

func (m *AddRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRemoteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteUserRequest) Reset()         { *m = UpdateRemoteUserRequest{} }
func (m *UpdateRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteUserRequest) ProtoMessage()    {}
func (*UpdateRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{19}
}

func (m *UpdateRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteUserRequest.Unmarshal(m, b)
}
func (m *UpdateRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteUserRequest.Merge(m, src)
}
func (m *UpdateRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteUserRequest.Size(m)
}
func (m *UpdateRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteUserRequest proto.InternalMessageInfo

func (m *UpdateRemoteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemoteUserResponse) Reset()         { *m = UpdateRemoteUserResponse{} }
func (m *UpdateRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRemoteUserResponse) ProtoMessage()    {}
func (*UpdateRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{20}
}

func (m *UpdateRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemoteUserResponse.Unmarshal(m, b)
}
func (m *UpdateRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemoteUserResponse.Merge(m, src)
}
func (m *UpdateRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRemoteUserResponse.Size(m)
}
func (m *UpdateRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemoteUserResponse proto.InternalMessageInfo

func (m *UpdateRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveRemoteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteUserRequest) Reset()         { *m = RemoveRemoteUserRequest{} }
func (m *RemoveRemoteUserRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteUserRequest) ProtoMessage()    {}
func (*RemoveRemoteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{21}
}

func (m *RemoveRemoteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteUserRequest.Unmarshal(m, b)
}
func (m *RemoveRemoteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteUserRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteUserRequest.Merge(m, src)
}
func (m *RemoveRemoteUserRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteUserRequest.Size(m)
}
func (m *RemoveRemoteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteUserRequest proto.InternalMessageInfo

func (m *RemoveRemoteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RemoveRemoteUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRemoteUserResponse) Reset()         { *m = RemoveRemoteUserResponse{} }
func (m *RemoveRemoteUserResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveRemoteUserResponse) ProtoMessage()    {}
func (*RemoveRemoteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62a533fe24d37ba7, []int{22}
}

func (m *RemoveRemoteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRemoteUserResponse.Unmarshal(m, b)
}
func (m *RemoveRemoteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRemoteUserResponse.Marshal(b, m, deterministic)
}
func (m *RemoveRemoteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRemoteUserResponse.Merge(m, src)
}
func (m *RemoveRemoteUserResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveRemoteUserResponse.Size(m)
}
func (m *RemoveRemoteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRemoteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRemoteUserResponse proto.InternalMessageInfo

func (m *RemoveRemoteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "spidProtoBuffers.User")
	proto.RegisterType((*GetUserRequest)(nil), "spidProtoBuffers.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "spidProtoBuffers.GetUserResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "spidProtoBuffers.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "spidProtoBuffers.RegisterUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "spidProtoBuffers.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "spidProtoBuffers.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "spidProtoBuffers.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "spidProtoBuffers.DeleteUserResponse")
	proto.RegisterType((*RequestAssociationRequest)(nil), "spidProtoBuffers.RequestAssociationRequest")
	proto.RegisterType((*RequestAssociationResponse)(nil), "spidProtoBuffers.RequestAssociationResponse")
	proto.RegisterType((*RequestDissociationRequest)(nil), "spidProtoBuffers.RequestDissociationRequest")
	proto.RegisterType((*RequestDissociationResponse)(nil), "spidProtoBuffers.RequestDissociationResponse")
	proto.RegisterType((*RequestSpidInfoRequest)(nil), "spidProtoBuffers.RequestSpidInfoRequest")
	proto.RegisterType((*RequestSpidInfoResponse)(nil), "spidProtoBuffers.RequestSpidInfoResponse")
	proto.RegisterType((*RequestLockChangeRequest)(nil), "spidProtoBuffers.RequestLockChangeRequest")
	proto.RegisterType((*RequestLockChangeResponse)(nil), "spidProtoBuffers.RequestLockChangeResponse")
	proto.RegisterType((*AddRemoteUserRequest)(nil), "spidProtoBuffers.AddRemoteUserRequest")
	proto.RegisterType((*AddRemoteUserResponse)(nil), "spidProtoBuffers.AddRemoteUserResponse")
	proto.RegisterType((*UpdateRemoteUserRequest)(nil), "spidProtoBuffers.UpdateRemoteUserRequest")
	proto.RegisterType((*UpdateRemoteUserResponse)(nil), "spidProtoBuffers.UpdateRemoteUserResponse")
	proto.RegisterType((*RemoveRemoteUserRequest)(nil), "spidProtoBuffers.RemoveRemoteUserRequest")
	proto.RegisterType((*RemoveRemoteUserResponse)(nil), "spidProtoBuffers.RemoveRemoteUserResponse")
}

func init() { proto.RegisterFile("userHandler.proto", fileDescriptor_62a533fe24d37ba7) }

var fileDescriptor_62a533fe24d37ba7 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x4f, 0xd4, 0x4e,
	0x14, 0xa5, 0xfb, 0xdb, 0x1f, 0xc2, 0x5d, 0xf9, 0xb3, 0x57, 0x84, 0x3a, 0xfa, 0xb0, 0x56, 0xd4,
	0x65, 0x51, 0x12, 0xd1, 0x47, 0x13, 0x03, 0xae, 0x01, 0x22, 0x0f, 0xa4, 0x48, 0x8c, 0xc4, 0x84,
	0x74, 0xdb, 0xd9, 0xa5, 0xa1, 0xb4, 0xa5, 0xd3, 0xf5, 0x73, 0xf9, 0xfd, 0x7c, 0x31, 0x9d, 0x76,
	0xbb, 0x6d, 0x67, 0xca, 0x56, 0xe8, 0x5b, 0x3b, 0x39, 0x73, 0xce, 0xb9, 0x77, 0xa6, 0xe7, 0x16,
	0xda, 0x63, 0x46, 0x83, 0x43, 0xc3, 0xb5, 0x1c, 0x1a, 0xec, 0xf8, 0x81, 0x17, 0x7a, 0xb8, 0xca,
	0x7c, 0xdb, 0x3a, 0x89, 0x1e, 0xf7, 0xc7, 0xc3, 0x21, 0x0d, 0x18, 0x51, 0x47, 0xd4, 0xa5, 0x81,
	0x6d, 0xf6, 0xe9, 0xd0, 0x76, 0xed, 0xd0, 0xf6, 0x5c, 0x16, 0x63, 0x49, 0x3b, 0xc2, 0xe6, 0xb6,
	0x6b, 0xbf, 0x15, 0x68, 0x9e, 0x31, 0x1a, 0xe0, 0x32, 0x34, 0x6c, 0x4b, 0x55, 0x3a, 0x4a, 0x77,
	0x51, 0x6f, 0xd8, 0x16, 0x22, 0x34, 0x5d, 0xe3, 0x9a, 0xaa, 0x0d, 0xbe, 0xc2, 0x9f, 0xf1, 0x23,
	0x2c, 0xf8, 0x1e, 0xe3, 0x94, 0xea, 0x7f, 0x1d, 0xa5, 0xdb, 0xda, 0xed, 0xec, 0x14, 0xe5, 0x77,
	0x0e, 0x1c, 0x6f, 0x60, 0x38, 0x27, 0x09, 0x4e, 0x4f, 0x77, 0x60, 0x07, 0x5a, 0x8e, 0xc1, 0xc2,
	0x33, 0xdf, 0x32, 0x42, 0x6a, 0xa9, 0x4d, 0x4e, 0x9c, 0x5d, 0xc2, 0x4d, 0x58, 0x32, 0xc7, 0x41,
	0x40, 0xdd, 0xf0, 0xd4, 0xb7, 0xad, 0xa3, 0xbe, 0xfa, 0x3f, 0xc7, 0xe4, 0x17, 0xb5, 0x2e, 0x2c,
	0x1f, 0xd0, 0x30, 0x32, 0xad, 0xd3, 0x9b, 0x31, 0x65, 0x21, 0xae, 0xc3, 0x7c, 0xd4, 0x98, 0xa3,
	0x7e, 0xe2, 0x3f, 0x79, 0xd3, 0xbe, 0xc3, 0x4a, 0x8a, 0x64, 0xbe, 0xe7, 0x32, 0x8a, 0x2a, 0x3c,
	0xb8, 0xa6, 0x8c, 0x19, 0x23, 0x9a, 0x60, 0x27, 0xaf, 0xd8, 0x83, 0x66, 0xb4, 0x8d, 0x17, 0xdc,
	0xda, 0x5d, 0x17, 0x0b, 0xe3, 0x3c, 0x1c, 0xa3, 0x8d, 0xe0, 0x91, 0x4e, 0x47, 0x36, 0x0b, 0x69,
	0x90, 0xf5, 0x31, 0xe9, 0x99, 0x52, 0xd2, 0xb3, 0xc6, 0xbf, 0xf6, 0x4c, 0xfb, 0x09, 0x6b, 0x79,
	0xa1, 0x5a, 0xcb, 0xf8, 0x04, 0xed, 0xb8, 0xf5, 0xd9, 0x22, 0x26, 0x04, 0x4a, 0x05, 0x82, 0x73,
	0xc0, 0x2c, 0x41, 0xad, 0xe6, 0xb6, 0xa1, 0xdd, 0xa7, 0x0e, 0xcd, 0x9b, 0x2b, 0x3b, 0xe9, 0x73,
	0xc0, 0x2c, 0xb8, 0x56, 0x23, 0x5f, 0xe1, 0x49, 0x22, 0xbf, 0xc7, 0x98, 0x67, 0xda, 0x06, 0x3f,
	0xa3, 0xdb, 0x0d, 0x45, 0xeb, 0x2c, 0xbe, 0xc3, 0xf1, 0x07, 0x94, 0xbc, 0x69, 0x03, 0x20, 0x32,
	0xb2, 0x5a, 0x0d, 0x1f, 0xa7, 0x1a, 0x7d, 0xfb, 0xfe, 0x8e, 0x4d, 0x78, 0x2a, 0x65, 0xab, 0xd5,
	0xf2, 0x21, 0xac, 0x27, 0x22, 0xfc, 0x23, 0x77, 0x87, 0xde, 0x5d, 0xed, 0x5e, 0xc0, 0x86, 0xc0,
	0x54, 0xc5, 0x6a, 0xb4, 0xbd, 0xdc, 0x6a, 0xc4, 0xa5, 0x73, 0x8c, 0x76, 0x09, 0x6a, 0x22, 0x70,
	0xec, 0x99, 0x57, 0x9f, 0x2f, 0x0d, 0x77, 0x44, 0xef, 0x68, 0x16, 0x9f, 0xc1, 0xa2, 0xe3, 0x99,
	0x57, 0xa7, 0xa1, 0x11, 0x52, 0x9e, 0xa8, 0x8b, 0xfa, 0x74, 0x41, 0x33, 0xd2, 0x8b, 0x97, 0x55,
	0xaa, 0xb5, 0x98, 0x7d, 0x58, 0xdb, 0xb3, 0x2c, 0x9d, 0x5e, 0x7b, 0x77, 0x0f, 0x81, 0x77, 0xf0,
	0xb8, 0xc0, 0x31, 0xcb, 0xa2, 0xf6, 0x05, 0x36, 0xe2, 0xdc, 0xb8, 0x9f, 0xf2, 0x07, 0x50, 0x45,
	0x9a, 0x2a, 0xe2, 0x11, 0xfe, 0xd7, 0xfd, 0xc5, 0x45, 0x9a, 0x59, 0xe2, 0xbb, 0x7f, 0x16, 0xa0,
	0x75, 0x36, 0x1d, 0xe2, 0xf8, 0x0d, 0x5a, 0xc9, 0x88, 0x8a, 0xae, 0x2a, 0xca, 0x66, 0x43, 0x6e,
	0xd6, 0x91, 0xe7, 0xb7, 0x20, 0x62, 0x75, 0x6d, 0x0e, 0x2f, 0xe0, 0x61, 0x76, 0x6c, 0xe0, 0x4b,
	0x71, 0x93, 0x64, 0x7e, 0x91, 0x57, 0xb3, 0x60, 0xa9, 0xc0, 0x0f, 0x80, 0x69, 0xf0, 0xe3, 0x0b,
	0x49, 0xa3, 0x8a, 0x73, 0x85, 0x6c, 0xde, 0x0e, 0xca, 0x52, 0x4f, 0xa3, 0x5c, 0x46, 0x2d, 0x4c,
	0x05, 0x19, 0xb5, 0x38, 0x0d, 0xb4, 0x39, 0xbc, 0x01, 0x14, 0xc3, 0x17, 0xb7, 0x65, 0x55, 0x97,
	0xe4, 0x3d, 0x79, 0x53, 0x0d, 0x9c, 0x4a, 0x86, 0xd1, 0x9f, 0x82, 0x90, 0x9e, 0x58, 0x4e, 0x23,
	0x89, 0x6c, 0xf2, 0xb6, 0x22, 0x3a, 0x55, 0xbd, 0x84, 0x95, 0x42, 0x08, 0x62, 0xb7, 0x94, 0xa3,
	0x90, 0xb8, 0x64, 0xab, 0x02, 0x32, 0x55, 0x72, 0xa1, 0x2d, 0x64, 0x14, 0xf6, 0x4a, 0x19, 0x84,
	0xc8, 0x24, 0xdb, 0x95, 0xb0, 0xa9, 0xde, 0x00, 0x96, 0x72, 0x61, 0x83, 0x92, 0x3b, 0x2b, 0x4b,
	0x34, 0xf2, 0x7a, 0x26, 0x2e, 0xd5, 0xb8, 0x82, 0xd5, 0x62, 0xac, 0xe0, 0x56, 0xd9, 0xed, 0x15,
	0x95, 0x7a, 0x55, 0xa0, 0x59, 0xb1, 0x62, 0x8c, 0xa0, 0xf4, 0x04, 0xa4, 0x89, 0x45, 0x7a, 0x55,
	0xa0, 0x13, 0xb1, 0xc1, 0x3c, 0xff, 0xe9, 0x7f, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0x87, 0xeb,
	0x6f, 0xd3, 0x48, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserHandlerClient is the client API for UserHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserHandlerClient interface {
	GetUserInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	RequestAssociation(ctx context.Context, in *RequestAssociationRequest, opts ...grpc.CallOption) (*RequestAssociationResponse, error)
	RequestDissociation(ctx context.Context, in *RequestDissociationRequest, opts ...grpc.CallOption) (*RequestDissociationResponse, error)
	RequestSpidInfo(ctx context.Context, in *RequestSpidInfoRequest, opts ...grpc.CallOption) (*RequestSpidInfoResponse, error)
	RequestLockChange(ctx context.Context, in *RequestLockChangeRequest, opts ...grpc.CallOption) (*RequestLockChangeResponse, error)
	AddRemoteUser(ctx context.Context, in *AddRemoteUserRequest, opts ...grpc.CallOption) (*AddRemoteUserResponse, error)
	UpdateRemoteUser(ctx context.Context, in *UpdateRemoteUserRequest, opts ...grpc.CallOption) (*UpdateRemoteUserResponse, error)
	RemoveRemoteUser(ctx context.Context, in *RemoveRemoteUserRequest, opts ...grpc.CallOption) (*RemoveRemoteUserResponse, error)
}

type userHandlerClient struct {
	cc *grpc.ClientConn
}

func NewUserHandlerClient(cc *grpc.ClientConn) UserHandlerClient {
	return &userHandlerClient{cc}
}

func (c *userHandlerClient) GetUserInfo(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RequestAssociation(ctx context.Context, in *RequestAssociationRequest, opts ...grpc.CallOption) (*RequestAssociationResponse, error) {
	out := new(RequestAssociationResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RequestAssociation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RequestDissociation(ctx context.Context, in *RequestDissociationRequest, opts ...grpc.CallOption) (*RequestDissociationResponse, error) {
	out := new(RequestDissociationResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RequestDissociation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RequestSpidInfo(ctx context.Context, in *RequestSpidInfoRequest, opts ...grpc.CallOption) (*RequestSpidInfoResponse, error) {
	out := new(RequestSpidInfoResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RequestSpidInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RequestLockChange(ctx context.Context, in *RequestLockChangeRequest, opts ...grpc.CallOption) (*RequestLockChangeResponse, error) {
	out := new(RequestLockChangeResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RequestLockChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) AddRemoteUser(ctx context.Context, in *AddRemoteUserRequest, opts ...grpc.CallOption) (*AddRemoteUserResponse, error) {
	out := new(AddRemoteUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/AddRemoteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) UpdateRemoteUser(ctx context.Context, in *UpdateRemoteUserRequest, opts ...grpc.CallOption) (*UpdateRemoteUserResponse, error) {
	out := new(UpdateRemoteUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/UpdateRemoteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) RemoveRemoteUser(ctx context.Context, in *RemoveRemoteUserRequest, opts ...grpc.CallOption) (*RemoveRemoteUserResponse, error) {
	out := new(RemoveRemoteUserResponse)
	err := c.cc.Invoke(ctx, "/spidProtoBuffers.UserHandler/RemoveRemoteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserHandlerServer is the server API for UserHandler service.
type UserHandlerServer interface {
	GetUserInfo(context.Context, *GetUserRequest) (*GetUserResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	RequestAssociation(context.Context, *RequestAssociationRequest) (*RequestAssociationResponse, error)
	RequestDissociation(context.Context, *RequestDissociationRequest) (*RequestDissociationResponse, error)
	RequestSpidInfo(context.Context, *RequestSpidInfoRequest) (*RequestSpidInfoResponse, error)
	RequestLockChange(context.Context, *RequestLockChangeRequest) (*RequestLockChangeResponse, error)
	AddRemoteUser(context.Context, *AddRemoteUserRequest) (*AddRemoteUserResponse, error)
	UpdateRemoteUser(context.Context, *UpdateRemoteUserRequest) (*UpdateRemoteUserResponse, error)
	RemoveRemoteUser(context.Context, *RemoveRemoteUserRequest) (*RemoveRemoteUserResponse, error)
}

// UnimplementedUserHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedUserHandlerServer struct {
}

func (*UnimplementedUserHandlerServer) GetUserInfo(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedUserHandlerServer) RegisterUser(ctx context.Context, req *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserHandlerServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserHandlerServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserHandlerServer) RequestAssociation(ctx context.Context, req *RequestAssociationRequest) (*RequestAssociationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAssociation not implemented")
}
func (*UnimplementedUserHandlerServer) RequestDissociation(ctx context.Context, req *RequestDissociationRequest) (*RequestDissociationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDissociation not implemented")
}
func (*UnimplementedUserHandlerServer) RequestSpidInfo(ctx context.Context, req *RequestSpidInfoRequest) (*RequestSpidInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSpidInfo not implemented")
}
func (*UnimplementedUserHandlerServer) RequestLockChange(ctx context.Context, req *RequestLockChangeRequest) (*RequestLockChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestLockChange not implemented")
}
func (*UnimplementedUserHandlerServer) AddRemoteUser(ctx context.Context, req *AddRemoteUserRequest) (*AddRemoteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRemoteUser not implemented")
}
func (*UnimplementedUserHandlerServer) UpdateRemoteUser(ctx context.Context, req *UpdateRemoteUserRequest) (*UpdateRemoteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemoteUser not implemented")
}
func (*UnimplementedUserHandlerServer) RemoveRemoteUser(ctx context.Context, req *RemoveRemoteUserRequest) (*RemoveRemoteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRemoteUser not implemented")
}

func RegisterUserHandlerServer(s *grpc.Server, srv UserHandlerServer) {
	s.RegisterService(&_UserHandler_serviceDesc, srv)
}

func _UserHandler_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).GetUserInfo(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RequestAssociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAssociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RequestAssociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RequestAssociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RequestAssociation(ctx, req.(*RequestAssociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RequestDissociation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDissociationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RequestDissociation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RequestDissociation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RequestDissociation(ctx, req.(*RequestDissociationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RequestSpidInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSpidInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RequestSpidInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RequestSpidInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RequestSpidInfo(ctx, req.(*RequestSpidInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RequestLockChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLockChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RequestLockChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RequestLockChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RequestLockChange(ctx, req.(*RequestLockChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_AddRemoteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).AddRemoteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/AddRemoteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).AddRemoteUser(ctx, req.(*AddRemoteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_UpdateRemoteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemoteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).UpdateRemoteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/UpdateRemoteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).UpdateRemoteUser(ctx, req.(*UpdateRemoteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_RemoveRemoteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRemoteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).RemoveRemoteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spidProtoBuffers.UserHandler/RemoveRemoteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).RemoveRemoteUser(ctx, req.(*RemoveRemoteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spidProtoBuffers.UserHandler",
	HandlerType: (*UserHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserHandler_GetUserInfo_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _UserHandler_RegisterUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserHandler_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserHandler_DeleteUser_Handler,
		},
		{
			MethodName: "RequestAssociation",
			Handler:    _UserHandler_RequestAssociation_Handler,
		},
		{
			MethodName: "RequestDissociation",
			Handler:    _UserHandler_RequestDissociation_Handler,
		},
		{
			MethodName: "RequestSpidInfo",
			Handler:    _UserHandler_RequestSpidInfo_Handler,
		},
		{
			MethodName: "RequestLockChange",
			Handler:    _UserHandler_RequestLockChange_Handler,
		},
		{
			MethodName: "AddRemoteUser",
			Handler:    _UserHandler_AddRemoteUser_Handler,
		},
		{
			MethodName: "UpdateRemoteUser",
			Handler:    _UserHandler_UpdateRemoteUser_Handler,
		},
		{
			MethodName: "RemoveRemoteUser",
			Handler:    _UserHandler_RemoveRemoteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userHandler.proto",
}
