// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spidHandler.proto

package requestHandling

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a781e8f047de7a, []int{0}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ClientRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ServerResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16a781e8f047de7a, []int{1}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ServerResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientRequest)(nil), "ClientRequest")
	proto.RegisterType((*ServerResponse)(nil), "ServerResponse")
}

func init() { proto.RegisterFile("spidHandler.proto", fileDescriptor_16a781e8f047de7a) }

var fileDescriptor_16a781e8f047de7a = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x9d, 0x38, 0x88, 0x73, 0x47, 0x2b, 0x66, 0x55, 0x5c, 0x49, 0x57, 0xae, 0xea, 0x1f,
	0xe8, 0x5e, 0x85, 0x51, 0x70, 0x63, 0x06, 0xc1, 0x9d, 0x74, 0xcc, 0x51, 0xc3, 0x94, 0x24, 0x26,
	0x77, 0x84, 0xbe, 0x9f, 0x0f, 0x26, 0x69, 0x41, 0xe9, 0x2e, 0xbb, 0xcb, 0x21, 0xdf, 0x77, 0x0e,
	0x84, 0x64, 0xf4, 0x46, 0xbf, 0x7e, 0x36, 0x56, 0xb7, 0x08, 0xb5, 0x0f, 0x8e, 0x5d, 0xb5, 0xa0,
	0xfd, 0xdb, 0xd6, 0xc0, 0xb2, 0xc2, 0xd7, 0x06, 0x91, 0x65, 0x41, 0xc2, 0xe8, 0x72, 0x72, 0x3c,
	0x39, 0x99, 0x29, 0x61, 0xb4, 0x94, 0x34, 0xe5, 0xce, 0xa3, 0x14, 0x7d, 0xd2, 0xdf, 0x29, 0x5b,
	0x39, 0xdd, 0x95, 0xdb, 0x43, 0x96, 0xee, 0xea, 0x85, 0x8a, 0x25, 0xc2, 0x37, 0x82, 0x42, 0xf4,
	0xce, 0x46, 0x64, 0x99, 0x0a, 0x12, 0x6e, 0xdd, 0x7b, 0x76, 0x95, 0x70, 0xeb, 0x3f, 0xf3, 0xf4,
	0xdf, 0x7c, 0xf1, 0x23, 0x68, 0xbe, 0xf4, 0x46, 0xdf, 0x0f, 0xc3, 0x65, 0x4d, 0xb3, 0xa7, 0x0d,
	0x42, 0x97, 0x32, 0x59, 0xd4, 0xa3, 0xf9, 0x47, 0x07, 0xf5, 0x78, 0x45, 0xb5, 0x25, 0xcf, 0x68,
	0xbe, 0x00, 0xa7, 0xd7, 0x0f, 0xf6, 0xdd, 0xe5, 0x10, 0xe7, 0xb4, 0xa7, 0xf0, 0x61, 0x22, 0x23,
	0xe4, 0x96, 0x5c, 0xd1, 0xe1, 0xb3, 0xd7, 0x0d, 0xe3, 0xa6, 0x61, 0x46, 0xe8, 0x72, 0xab, 0xae,
	0x49, 0x0e, 0x5c, 0x2a, 0x7a, 0x74, 0x6f, 0x0d, 0x1b, 0x67, 0x73, 0xc0, 0x53, 0xa2, 0x3b, 0xb4,
	0x18, 0xc0, 0x0c, 0x60, 0xb5, 0xd3, 0x7f, 0xf8, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43,
	0xd1, 0x0f, 0xb7, 0x06, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpidHandlerClient is the client API for SpidHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpidHandlerClient interface {
	GetSpidInfo(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error)
	RegisterSpid(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error)
	UpdateBatteryInfo(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error)
	UpdateSpidLocation(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error)
	DeleteSpid(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error)
}

type spidHandlerClient struct {
	cc *grpc.ClientConn
}

func NewSpidHandlerClient(cc *grpc.ClientConn) SpidHandlerClient {
	return &spidHandlerClient{cc}
}

func (c *spidHandlerClient) GetSpidInfo(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/SpidHandler/GetSpidInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) RegisterSpid(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/SpidHandler/RegisterSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) UpdateBatteryInfo(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/SpidHandler/UpdateBatteryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) UpdateSpidLocation(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/SpidHandler/UpdateSpidLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spidHandlerClient) DeleteSpid(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/SpidHandler/DeleteSpid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpidHandlerServer is the server API for SpidHandler service.
type SpidHandlerServer interface {
	GetSpidInfo(context.Context, *ClientRequest) (*ServerResponse, error)
	RegisterSpid(context.Context, *ClientRequest) (*ServerResponse, error)
	UpdateBatteryInfo(context.Context, *ClientRequest) (*ServerResponse, error)
	UpdateSpidLocation(context.Context, *ClientRequest) (*ServerResponse, error)
	DeleteSpid(context.Context, *ClientRequest) (*ServerResponse, error)
}

// UnimplementedSpidHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedSpidHandlerServer struct {
}

func (*UnimplementedSpidHandlerServer) GetSpidInfo(ctx context.Context, req *ClientRequest) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpidInfo not implemented")
}
func (*UnimplementedSpidHandlerServer) RegisterSpid(ctx context.Context, req *ClientRequest) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSpid not implemented")
}
func (*UnimplementedSpidHandlerServer) UpdateBatteryInfo(ctx context.Context, req *ClientRequest) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatteryInfo not implemented")
}
func (*UnimplementedSpidHandlerServer) UpdateSpidLocation(ctx context.Context, req *ClientRequest) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpidLocation not implemented")
}
func (*UnimplementedSpidHandlerServer) DeleteSpid(ctx context.Context, req *ClientRequest) (*ServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSpid not implemented")
}

func RegisterSpidHandlerServer(s *grpc.Server, srv SpidHandlerServer) {
	s.RegisterService(&_SpidHandler_serviceDesc, srv)
}

func _SpidHandler_GetSpidInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpidHandler/GetSpidInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).GetSpidInfo(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_RegisterSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpidHandler/RegisterSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).RegisterSpid(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_UpdateBatteryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).UpdateBatteryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpidHandler/UpdateBatteryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).UpdateBatteryInfo(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_UpdateSpidLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).UpdateSpidLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpidHandler/UpdateSpidLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).UpdateSpidLocation(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpidHandler_DeleteSpid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpidHandler/DeleteSpid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpidHandlerServer).DeleteSpid(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpidHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SpidHandler",
	HandlerType: (*SpidHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpidInfo",
			Handler:    _SpidHandler_GetSpidInfo_Handler,
		},
		{
			MethodName: "RegisterSpid",
			Handler:    _SpidHandler_RegisterSpid_Handler,
		},
		{
			MethodName: "UpdateBatteryInfo",
			Handler:    _SpidHandler_UpdateBatteryInfo_Handler,
		},
		{
			MethodName: "UpdateSpidLocation",
			Handler:    _SpidHandler_UpdateSpidLocation_Handler,
		},
		{
			MethodName: "DeleteSpid",
			Handler:    _SpidHandler_DeleteSpid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spidHandler.proto",
}
